BEGIN

    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, '0',    1, 'Select one...'); 
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'AC',   2, 'AC - AIR TRAFFIC CONTROL EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'AF',   3, 'AF - FIXED WING');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'AL',   4, 'AL - AVIATION LIFE SUPPORT EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'AR',   5, 'AR - ROTARY WING');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'AT',   6, 'AT - TRAINING FLIGHT SIMULATOR TRAINER');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'AX',   7, 'AX - ANCILLARY EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'AZ',   8, 'AZ - TOOLS AND TEST EQUIPMENT/TRAINING AIDS/DEVICES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'BA',   9, 'BA - HAWK (SP)');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'BB',  10, 'BB - HERCULES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'BC',  11, 'BC - HAWK (IMPROVED)');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'BD',  12, 'BD - AN/TSQ-73');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'BE',  13, 'BE - GM SYSTEM HAWK');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'BF',  14, 'BF - ARMAMENT SUBSYSTEM HELICOPTER M-22');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'BJ',  15, 'BJ - REDEYE');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'BK',  16, 'BK - CHAPARRAL');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'BL',  17, 'BL - DATA CONVERTER AIR DEFENSE SYSTEM');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'BM',  18, 'BM - LIGHT SPECIAL DIVISION INTERIM SENSOR (LSDIS)');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'BN',  19, 'BN - STINGER');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'BP',  20, 'BP - PATRIOT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'BQ',  21, 'BQ - AVENGER');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'BR',  22, 'BR - ROLAND');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'BT',  23, 'BT - TARGET MISSILE SYSTEMS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'BU',  24, 'BU - GUIDED MISSILE SYSTEMS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'BV',  25, 'BV - MISCELLANEOUS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'BX',  26, 'BX - TRAINING AND HANDLING EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'BZ',  27, 'BZ - TOOLS AND TEST EQUIPMENT/TRAINING AIDS/DEVICES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'CA',  28, 'CA - LAND COMBAT SUPPORT SYSTEM (LCSS)');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'CB',  29, 'CB - TOW');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'CC',  30, 'CC - TOW II');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'CD',  31, 'CD - DRAGON');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'CE',  32, 'CE - SLUFAE');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'CF',  33, 'CF - G/VLLD M981 G/VLLD GROUND');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'CG',  34, 'CG - MULTIPLE ROCKET LAUNCHER SYSTEM (MLRS)');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'CH',  35, 'CH - HELLFIRE');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'CJ',  36, 'CJ - MAST MOUNTED SIGHT (MMS)');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'CL',  37, 'CL - LANCE');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'CN',  38, 'CN - HONEST JOHN');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'CP',  39, 'CP - AIR-TO-AIR STINGER');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'CQ',  40, 'CQ - LITTLE JOHN');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'CT',  41, 'CT - GM BATT CONT CENT-PER');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'CU',  42, 'CU - CARR');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'CV',  43, 'CV - SHILLELAGH');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'CW',  44, 'CW - SERGEANT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'CX',  45, 'CX - TRAINING AND HANDLING EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'CY',  46, 'CY - MISCELLANEOUS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'CZ',  47, 'CZ - TOOLS AND TEST EQUIPMENT/TRAINING AIDS/DEVICES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'DA',  48, 'DA - TOWED HOWITZERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'DB',  49, 'DB - MORTARS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'DC',  50, 'DC - RECOILLESS RIFLES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'DD',  51, 'DD - RECOILLESS GUNS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'DE',  52, 'DE - ROCKET LAUNCHERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'DF',  53, 'DF - COMPUTER GUNS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'DG',  54, 'DG - ANTI-AIRCRAFT GUNS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'DX',  55, 'DX - TRAINING EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'DZ',  56, 'DZ - TOOLS AND TEST EQUIPMENT/TRAINING AIDS/DEVICES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'EA',  57, 'EA - ARMAMENT SUBSYSTEMS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'EB',  58, 'EB - RIFLES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'EC',  59, 'EC - MACHINE GUNS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'ED',  60, 'ED - GRENADE LAUNCHERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'EE',  61, 'EE - SUBMACHINE GUNS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'EF',  62, 'EF - AUTOMATIC GUNS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'EG',  63, 'EG - ROCKET LAUNCHERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'EH',  64, 'EH - CARBINES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'EI',  65, 'EI - GUNS OTHER');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'EJ',  66, 'EJ - HANDGUNS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'EK',  67, 'EK - SHOTGUNS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'EM',  68, 'EM - SMALL ARMS OTHER');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'EX',  69, 'EX - ANCILLARY EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'EY',  70, 'EY - MISCELLANEOUS SUPPORT EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'EZ',  71, 'EZ - TOOLS AND TEST EQUIPMENT/TRAINING AIDS/DEVICES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'FA',  72, 'FA - 76MM');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'FB',  73, 'FB - 90MM 105MM 120MM');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'FC',  74, 'FC - 152MM');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'FX',  75, 'FX - TRAINING EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'FZ',  76, 'FZ - TOOLS AND TEST EQUIPMENT/TRAINING AIDS/DEVICES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'GA',  77, 'GA - SELF-PROPELLED HOWITZERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'GB',  78, 'GB - SELF-PROPELLED MORTARS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'GC',  79, 'GC - COMBAT VEHICLE ANTI-TANK');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'GD',  80, 'GD - SELF-PROPELLED GUNS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'GE',  81, 'GE - COMBAT WHEELED VEHICLES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'GF',  82, 'GF - RECOVERY VEHICLES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'GG',  83, 'GG - COMBAT ENGINEER VEHICLES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'GJ',  84, 'GJ - TRACTORS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'GK',  85, 'GK - LAUNCHER BRIDGE');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'GL',  86, 'GL - CARRIER PERSONNEL');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'GM',  87, 'GM - ARMORED RECONNAISSANCE AIRBORNE ASSAULT VEHICLES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'GN',  88, 'GN - AMPHIBIOUS CARGO CARRIERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'GP',  89, 'GP - CARRIERS COMMAND RECONNAISSANCE');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'GQ',  90, 'GQ - CARRIERS COMMAND POST');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'GR',  91, 'GR - CARRIERS  CARGO TRACKED');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'GS',  92, 'GS - CARRIERS FLAMETHROWER (M132A1)');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'GW',  93, 'GW - CARRIERS OTHER');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'GX',  94, 'GX - ANCILLARY EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'GZ',  95, 'GZ - TOOLS AND TEST EQUIPMENT/TRAINING AIDS/DEVICES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'HA',  96, 'HA - TRUCKS 1/4 TON AMBULANCE');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'HB',  97, 'HB - TRUCKS 1/4 TON UTILITY');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'HC',  98, 'HC - TRUCKS 1/2 TON UTILITY');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'HD',  99, 'HD - TRUCKS 3/4 TON CARGO');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'HE', 101, 'HE - TRUCKS 3/4 TON OTHER');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'HF', 102, 'HF - TRUCKS 1 1/4 TON');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'HG', 103, 'HG - TRUCKS 2 1/2 TON CARGO');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'HH', 104, 'HH - TRUCKS 2 1/2 TON OTHER');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'HI', 105, 'HI - TRUCKS 5-TON CARGO');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'HJ', 106, 'HJ - TRUCKS 5-TON OTHER');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'HK', 107, 'HK - TRUCKS 8-TON');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'HL', 108, 'HL - TRUCKS 10-TON');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'HM', 109, 'HM - TRUCKS 12 TO 25 TONS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'HO', 110, 'HO - TRUCKS OVER 25 TON');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'HP', 111, 'HP - CARRIERS UTILITY ARTICULATED');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'HQ', 112, 'HQ - ARMORED CARS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'HR', 113, 'HR - ARMORED SECURITY VEHICLES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'HS', 114, 'HS - SEMI-TRAILERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'HT', 115, 'HT - TRAILERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'HU', 116, 'HU - TRUCK CHASSIS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'HV', 117, 'HV - LIGHT ARMORED VEHICLES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'HW', 118, 'HW - TRAILER CHASSIS (ALL)');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'HX', 119, 'HX - SLEDS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'HY', 120, 'HY - DOLLIES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'HZ', 121, 'HZ - TOOLS AND TEST EQUIPMENT/TRAINING AIDS/DEVICES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'JA', 122, 'JA - INFRARED SURVEILLANCE SYSTEMS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'JB', 123, 'JB - COMMUNICATIONS SECURITY EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'JC', 124, 'JC - TELEPHONE-TELEGRAPH TERMINALS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'JD', 125, 'JD - RADIAC SETS AND METERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'JE', 126, 'JE - SPECIAL USE INTELLIGENCE EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'JF', 127, 'JF - INTERROGATOR SETS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'JG', 128, 'JG - TELETYPEWRITERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'JH', 129, 'JH - SIGINT/EW EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'JI', 130, 'JI - INTERCOMMUNICATION SETS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'JJ', 100, 'JJ - INTRUSION DETECTIONS SYSTEMS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'JL', 100, 'JL - LASERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'JM', 100, 'JM - METEOROLOGICAL');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'JP', 100, 'JP - RADAR');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'JR', 100, 'JR - RADIOS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'JS', 100, 'JS - OPERATION CENTRAL COMMUNICATIONS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'JT', 100, 'JT - TRANSMITTERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'JU', 100, 'JU - RECEIVERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'JX', 100, 'JX - ANCILLARY EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'JY', 100, 'JY - DIGITAL COMPUTER SYSTEMS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'JZ', 100, 'JZ - TOOLS AND TEST EQUIPMENT/TRAINING AIDS/DEVICES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'KA', 100, 'KA - EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'KB', 100, 'KB - METERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'KC', 100, 'KC - ANALYZERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'KD', 100, 'KD - WIRE COMMUNICATIONS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'KE', 100, 'KE - RADIAC EQUIPMENT/RADIAC TEST EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'KF', 100, 'KF - METEOROLOGICAL');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'KH', 100, 'KH - AVIONICS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'KJ', 100, 'KJ - COMPUTERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'KK', 100, 'KK - CHARGERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'KL', 100, 'KL - SIGNAL GENERATORS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'KY', 100, 'KY - MISCELLANEOUS SUPPORT EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'KZ', 100, 'KZ - TOOLS AND TEST EQUIPMENT/TRAINING AIDS/DEVICES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'LA', 100, 'LA - BARGES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'LB', 100, 'LB - BOATS BRIDGING');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'LC', 100, 'LC - BOATS PASSENGER PICKETS AND UTILITY');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'LD', 100, 'LD - LANDING CRAFTS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'LE', 100, 'LE - TUGS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'LF', 100, 'LF - VESSELS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'LG', 100, 'LG - PROPELLING UNITS OUTBOARD');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'LH', 100, 'LH - BARGE CRANES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'LJ', 100, 'LJ - BOATS TRAILERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'LK', 100, 'LK - BOATS RECREATIONAL');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'LL', 100, 'LL - LIGHTER AMPHIBIOUS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'LM', 100, 'LM - TRANSPORT MOBILE ASSAULT BRIDGE');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'LN', 100, 'LN - BOATS ASSAULT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'LP', 100, 'LP - BOATS RECONNAISSANCE');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'LX', 100, 'LX - ANCILLARY EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'LY', 100, 'LY - MISCELLANEOUS FLOATING EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'LZ', 100, 'LZ - TOOLS AND TEST EQUIPMENT/TRAINING AIDS/DEVICES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'MA', 100, 'MA - CARS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'MB', 100, 'MB - MAINTENANCE CARS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'MC', 100, 'MC - DIESEL LOCOMOTIVES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'MD', 100, 'MD - CRANES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'ME', 100, 'ME - OTHER');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'MX', 100, 'MX - ANCILLARY EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'MZ', 100, 'MZ - TOOLS AND TEST EQUIPMENT/TRAINING AIDS/DEVICES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'NA', 100, 'NA - CRUSHERS AND PLANTS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'NB', 100, 'NB - PAVING EQUIPMENT/MIXERS/DISTRIBUTORS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'NC', 100, 'NC - EARTHMOVING');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'ND', 100, 'ND - TRACTORS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'NE', 100, 'NE - GRADERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'NF', 100, 'NF - CRANES/SHOVELS/EXCAVATORS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'NG', 100, 'NG - LOADERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'NH', 100, 'NH - ROLLERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'NJ', 100, 'NJ - DRILLS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'NK', 100, 'NK - BRIDGES  ERECTION AND FERRY');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'NL', 100, 'NL - BRIDGES  ARMOR VEHICLE LAUNCH');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'NM', 100, 'NM - SPREADERS (ALL TYPES)');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'NN', 100, 'NN - TRUCKS (CCE)');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'N0', 100, 'NO - BRIDGES FLOATING');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'NP', 100, 'NP - HEATERS/KETTLES HEATING BITUMINOUS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'NS', 100, 'NS - LANDING MAT SETS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'NT', 100, 'NT - HEATERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'NU', 100, 'NU - CONVEYORS/ELEVATORS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'NV', 100, 'NV - SPECIAL/MISCELLANEOUS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'NX', 100, 'NX - ANCILLARY EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'NZ', 100, 'NZ - TOOLS AND TEST EQUIPMENT/TRAINING AIDS/DEVICES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, '0A', 100, 'OA - ANESTHESIA APPARATUS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, '0B', 100, 'OB - BLOOD GAS APPARATUS/ANALYZERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, '0C', 100, 'OC - CENTRIFUGES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, '0D', 100, 'OD - X-RAY FILM PROCESSING SYSTEMS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, '0E', 100, 'OE - DEFIBRILLATORS/MONITORS/DIAGNOSTIC');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, '0F', 100, 'OF - DENTAL OPERATING UNITS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, '0G', 100, 'OG - MEDICAL COMPRESSORS/DEHYDRATORS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, '0H', 100, 'OH - TABLE OPERATING FIELD');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, '0I', 100, 'OI - RADIOGRAPHICS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, '0J', 100, 'OJ - BIOLOGICAL REFRIGERATORS/FREEZERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, '0K', 100, 'OK - RESPIRATORS/VENTILATORS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, '0L', 100, 'OL - HOSPITAL SINKS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, '0M', 100, 'OM - STERILIZATION EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, '0N', 100, 'ON - SUCTION AND PRESSURE APPARATUS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, '0O', 100, 'OO - MEDICAL EQUIPMENT SETS (MES/MMS/DES)');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, '0Q', 100, 'OQ - X-RAY APPARATUS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, '0R', 100, 'OR - MISCELLANEOUS/GENERAL');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, '0S', 100, 'OS - SURGICAL');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, '0T', 100, 'OT - MEDICAL OPHTHALMIC/OPTICAL');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, '0U', 100, 'OU - ENVIRONMENTAL/BIOLOGICAL DETECTION');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, '0V', 100, 'OV - ENDOSCOPES/BRONCHOSCOPES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, '0W', 100, 'OW - MEDICAL LABORATORY');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, '0X', 100, 'OX - ANCILLARY EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, '0Z', 100, 'OZ - TOOLS AND TEST EQUIPMENT/TRAINING AIDS/DEVICES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'PA', 100, 'PA - CRANES WAREHOUSE');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'PB', 100, 'PB - TRUCKS FORKLIFT  ELECTRIC');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'PC', 100, 'PC - TRUCKS FORKLIFT GED');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'PD', 100, 'PD - TRUCKS  PLATFORM');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'PE', 100, 'PE - TRACTORS WAREHOUSE');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'PF', 100, 'PF - TRUCKS STRADDLE');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'PG', 100, 'PG - TRUCKS FORKLIFT-ROUGH TERRAIN');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'PH', 100, 'PH - TRUCKS FORKLIFT-AIR MOBILE');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'PI', 100, 'PI - TRUCKS FORKLIFT-OTHER DED');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'PJ', 100, 'PJ - TRUCKS  STOCK SELECTOR');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'PK', 100, 'PK - TRUCKS CRANES 140 TON OR OVER');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'PL', 100, 'PL - TRUCKS FORKLIFTS OTHER');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'PM', 100, 'PM - HOISTS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'PN', 100, 'PN - CRANES FLOOR AND OVERHEAD');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'P0', 100, 'PO - CONVEYORS ');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'PP', 100, 'PP - HAND TRUCKS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'PQ', 100, 'PQ - RAMP DOCKS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'PR', 100, 'PR - TRAILERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'PS', 100, 'PS - TRUCKS MATERIAL HANDLING');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'PT', 100, 'PT - PALLET JACKS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'PX', 100, 'PX - ANCILLARY EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'PY', 100, 'PY - MISCELLANEOUS SUPPORT EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'PZ', 100, 'PZ - TOOLS AND TEST EQUIPMENT/TRAINING AIDS/DEVICES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'QA', 100, 'QA - BAKERY');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'QB', 100, 'QB - GENERATORS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'QC', 100, 'QC - COMPRESSORS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'QD', 100, 'QD - TANK/PUMP UNITS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'QE', 100, 'QE - LAUNDRY UNITS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'QF', 100, 'QF - AIR CONDITIONERS (TRLR MTD)');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'QG', 100, 'QG - WELDING MACHINES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'QH', 100, 'QH - LUBRICATING AND SERVICING UNITS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'QI', 100, 'QI - LIQUID OXYGEN CONVERTERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'QJ', 100, 'QJ - WATER PURIFICATION UNITS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'QK', 100, 'QK - GENERATING AND CHARGING PLANTS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'QL', 100, 'QL - ELEVATORS HYDRAULIC (GUIDED MISSILE)');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'QM', 100, 'QM - CHEMICAL PROTECTION');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'QN', 100, 'QN - LIGHTING EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'QP', 100, 'QP - POWER PLANTS/UNITS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'QQ', 100, 'QQ - REPRODUCTION EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'QR', 100, 'QR - TOPOGRAPHY/MEASURING/SURVEYING/MAPPING');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'QS', 100, 'QS - REPAIR SHOP EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'QT', 100, 'QT - SPECIAL REPAIR AND UTILITIES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'QU', 100, 'QU - FIREFIGHTING EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'QV', 100, 'QV - SPECIAL SHOP EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'QW', 100, 'QW - DETECTION EQUIPMENT/RECON SYSTEM/BIO-AGENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'QX', 100, 'QX - REFRIGERATION');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'QY', 100, 'QY - MISCELLANEOUS SUPPORT EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'QZ', 100, 'QZ - TOOLS AND TEST EQUIPMENT/TRAINING AIDS/DEVICES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'RA', 100, 'RA - PUNCH PRIMERS ETC.');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'RB', 100, 'RB - PROTECTION DEVICES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'RD', 100, 'RD - FURNACES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'RE', 100, 'RE - DEVICES/FIXTURES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'RF', 100, 'RF - PANELS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'RG', 100, 'RG - PLANTS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'RH', 100, 'RH - TANKS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'RI', 100, 'RI - HOPPERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'RJ', 100, 'RJ - VACUUM CHAMBERS/SEPARATORS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'RK', 100, 'RK - SPECIAL EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'RL', 100, 'RL - AMMUNITION MATERIAL');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'RN', 100, 'RN - SELECTED AMMUNITION');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'RP', 100, 'RP - SPECIAL EOD TOOLS AND EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'RQ', 100, 'RQ - TEST AND HANDLING EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'RT', 100, 'RT - AMMUNITION PECULAIR EQUIPMENT (APE)');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'RZ', 100, 'RZ - TOOLS AND TEST EQUIPMENT/TRAINING AIDS/DEVICES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'SA', 100, 'SA - PHOTOGRAPHIC/TELEVISION');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'SB', 100, 'SB - PUBLIC ADDRESS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'SC', 100, 'SC - MAINTENANCE PLATFORMS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'SD', 100, 'SD - MEASURING');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'SE', 100, 'SE - TRAFFIC CONTROLS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'SF', 100, 'SF - CONDITIONER/POLISH SCRUBBING');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'SG', 100, 'SG - DRYERS/FILTERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'SH', 100, 'SH - DRIVER TRAINING/TESTING');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'SI', 100, 'SI - OPTICAL EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'SJ', 100, 'SJ - SAFETY');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'SK', 100, 'SK - VACUUM LENS COATING');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'SL', 100, 'SL - LABORATORY TABLES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'SM', 100, 'SM - PLASTIC PROCESSING');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'SN', 100, 'SN - ELECTRICAL CHARGES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'SO', 100, 'SO - LABORATORY EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'SP', 100, 'SP - LABORATORY EQUIPMENT - CONTINUED');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'SQ', 100, 'SQ - CHILLING MACHINES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'SR', 100, 'SR - COMMUNICATIONS - COMMERCIAL');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'SS', 100, 'SS - SHELTER/STRUCTURE');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'ST', 100, 'ST - PLATING/CLEANING TANKS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'SU', 100, 'SU - DUPLICATING MACHINES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'SV', 100, 'SV - PROJECTORS (MOVIE FILMS)');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'SW', 100, 'SW - RECORDER/REPRODUCER (AUDIO AND/OR VIDEO)');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'SX', 100, 'SX - ANCILLARY EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'SY', 100, 'SY - LAWN MOWERS SNOW REMOVAL GROUND MAINTENANCE AND OTHER MAINTENANCE AND SERVICES (M) EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'SZ', 100, 'SZ - TOOLS AND TEST EQUIPMENT/TRAINING AIDS/DEVICES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'TA', 100, 'TA - SAWS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'TB', 100, 'TB - LATHES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'TC', 100, 'TC - GRINDERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'TD', 100, 'TD - PLANERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'TE', 100, 'TE - SHAPERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'TF', 100, 'TF - FORMING MACHINES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'TG', 100, 'TG - SCREW MANUFACTURING MACHINES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'TH', 100, 'TH - THREADING MACHINES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'TJ', 100, 'TJ - SURFACERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'TK', 100, 'TK - BORING');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'TL', 100, 'TL - HONING');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'TM', 100, 'TM - MORTISERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'TN', 100, 'TN - JOINTERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'TO', 100, 'TO - ROUTERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'TP', 100, 'TP - BROACHING');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'TQ', 100, 'TQ - SHEAR/PUNCH/NOTCH');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'TR', 100, 'TR - CUTTERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'TS', 100, 'TS - SANDERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'TT', 100, 'TT - MILLING');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'TU', 100, 'TU - LAPPING');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'TV', 100, 'TV - PRESSES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'TW', 100, 'TW - DRILLS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'TX', 100, 'TX - SPECIAL');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'TY', 100, 'TY - ANCILLARY EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'TZ', 100, 'TZ - TOOLS AND TEST EQUIPMENT/TRAINING AIDS/DEVICES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'UA', 100, 'UA - HEAT TREATING');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'UC', 100, 'UC - CLEAN PAINT PROCESS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'UD', 100, 'UD - RUBBER PROCESS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'UE', 100, 'UE - PACKAGING AND PACKING');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'UF', 100, 'UF - TEXTILE/LEATHER');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'UG', 100, 'UG - JACKS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'UH', 100, 'UH - STORAGE EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'UI', 100, 'UI - LASER EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'UJ', 100, 'UJ - SCALES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'UK', 100, 'UK - FANS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'UL', 100, 'UL - TIRE AND WHEEL REPAIR');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'UM', 100, 'UM - VEHICLE TRACK PRESSES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'UN', 100, 'UN - LUBRICATING AIDS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'UP', 100, 'UP - HEATERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'UQ', 100, 'UQ - METALIZING EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'UR', 100, 'UR - REELS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'US', 100, 'US - DISTRIBUTION SYSTEMS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'UT', 100, 'UT - SPLICING EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'UU', 100, 'UU - POSITIONERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'UV', 100, 'UV - DRAFTING');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'UX', 100, 'UX - ANCILLARY EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'UZ', 100, 'UZ - TOOLS AND TEST EQUIPMENT/TRAINING AIDS/DEVICES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'VA', 100, 'VA - TRUCKS BOLSTER');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'VB', 100, 'VB - TRUCKS DUMP');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'VC', 100, 'VC - TRUCKS FIREFIGHTING');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'VD', 100, 'VD - TRUCKS HOPPER');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'VE', 100, 'VE - TRUCKS MAINTENANCE');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'VF', 100, 'VF - TRUCKS REFUSE/COLLECTIONS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'VG', 100, 'VG - TRUCKS TOPOGRAPHIC');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'VH', 100, 'VH - TRUCKS TANK');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'VI', 100, 'VI - TRUCKS STAKE');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'VJ', 100, 'VJ - TRUCKS TRACTOR (ALL TYPES)');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'VK', 100, 'VK - MISCELLANEOUS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'VL', 100, 'VL - PASSENGER CARRYING VEHICLES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'VM', 100, 'VM - SERVICING PLATFORMS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'VN', 100, 'VN - TRUCKS MULTIPURPOSE');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'VO', 100, 'VO - TRUCKS PANEL');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'VP', 100, 'VP - TRUCKS CARRYALL');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'VQ', 100, 'VQ - TRUCKS CARGO');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'VR', 100, 'VR - TRUCKS UTILITY');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'VS', 100, 'VS - TRUCKS SEWAGE');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'VT', 100, 'VT - TRUCKS OTHER');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'VU', 100, 'VU - TRAILERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'VV', 100, 'VV - SEMI-TRAILERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'VW', 100, 'VW - TRUCKS VAN');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'VX', 100, 'VX - TRUCKS REFRIGERATION');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'VY', 100, 'VY - TRUCKS WRECKER');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'VZ', 100, 'VZ - TOOLS AND TEST EQUIPMENT/TRAINING AIDS/DEVICES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'WA', 100, 'WA - DESKS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'WB', 100, 'WB - FILES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'WC', 100, 'WC - CABINETS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'WD', 100, 'WD - RUGS/CURTAINS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'WE', 100, 'WE - RANGES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'WF', 100, 'WF - REFRIGERATORS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'WG', 100, 'WG - FROZEN FOOD DISPLAYS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'WH', 100, 'WH - WATER COOLERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'WJ', 100, 'WJ - MUSICAL RELATED EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'WK', 100, 'WK - WASHING MACHINES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'WL', 100, 'WL - DRYERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'WM', 100, 'WM - LAUNDRY EXTRACTORS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'WN', 100, 'WN - ROTARY FILES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'WR', 100, 'WR - DAVENPORTS/COUCHES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'WS', 100, 'WS - FREEZERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'WT', 100, 'WT - KITCHEN EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'WU', 100, 'WU - CHAIRS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'WV', 100, 'WV - RELIGIOUS EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'WW', 100, 'WW - TABLES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'WZ', 100, 'WZ - TOOLS AND TEST EQUIPMENT/TRAINING AIDS/DEVICES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'XA', 100, 'XA - SAFES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'XB', 100, 'XB - MACHINES NOT LISTED ELSEWHERE');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'XC', 100, 'XC - TYPEWRITERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'XD', 100, 'XD - ADDRESSING PLATES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'XE', 100, 'XE - CALCULATING');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'XF', 100, 'XF - COMPUTING');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'XG', 100, 'XG - TIME/PAYROLL RECORDERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'XL', 100, 'XL - DICTATING');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'XM', 100, 'XM - PRODUCTION CONTROL BOARDS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'XN', 100, 'XN - DRAFTING TABLES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'XP', 100, 'XP - FLEXOWRITERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'XQ', 100, 'XQ - CASH REGISTERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'XR', 100, 'XR - SEALING UNITS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'XU', 100, 'XU - ENGRAVERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'XV', 100, 'XV - FABRICATORS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'XW', 100, 'XW - ENDORSERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'XX', 100, 'XX - FLAG CEREMONIAL');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'XY', 100, 'XY - MISCELLANEOUS SUPPORT EQUIPMENT ADP');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'XZ', 100, 'XZ - TOOLS AND TEST EQUIPMENT/TRAINING AIDS/DEVICES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'YA', 100, 'YA - ALIGNING');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'YB', 100, 'YB - COLLIMATORS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'YD', 100, 'YD - SAW FILERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'YE', 100, 'YE - MULTIPLE USE GAGES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'YF', 100, 'YF - METALIZING GUNS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'YG', 100, 'YG - HAMMERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'YH', 100, 'YH - JACKS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'YJ', 100, 'YJ - TOOL KITS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'YK', 100, 'YK - LIFTS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'YL', 100, 'YL - SPECIAL MACHINES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'YM', 100, 'YM - PULLERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'YN', 100, 'YN - RIVETERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'YP', 100, 'YP - TOOL SETS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'YQ', 100, 'YQ - WRENCHES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'YR', 100, 'YR - VISES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'YS', 100, 'YS - DIES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'YT', 100, 'YT - BORESCOPES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'YU', 100, 'YU - TWISTERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'YW', 100, 'YW - PUNCHES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'YZ', 100, 'YZ - HOSE EXPANDERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'ZA', 100, 'ZA - ANALYZERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'ZB', 100, 'ZB - SUPPORTERS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'ZD', 100, 'ZD - STANDS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'ZF', 100, 'ZF - STRAIN/STRESS MEASURING');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'ZH', 100, 'ZH - SPRINGS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'ZJ', 100, 'ZJ - VALVES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'ZK', 100, 'ZK - CLOTHING');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'ZL', 100, 'ZL - TEXTILES');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'ZM', 100, 'ZM - MUSEUM EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'ZN', 100, 'ZN - FOOTWEAR');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'ZP', 100, 'ZP - TENTS/CANVAS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'ZS', 100, 'ZS - MISCELLANEOUS');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, 'ZZ', 100, 'ZZ - GYM AND SPORT EQUIPMENT');
    INSERT INTO gb_pfsawh_code_ref (catcode, itemcode, codeSortOrder, itemtext) VALUES (1012, '-1', 999, 'Unknown');

    COMMIT; 
    
END; 

SELECT catcode, itemcode, codeSortOrder, itemtext 
FROM gb_pfsawh_code_ref 
WHERE catcode = 1012 
ORDER BY codeSortOrder;

