
DELETE FROM atis_awt_tasks;


INSERT INTO atis_awt_tasks (task_number, task_title, skill_level, subject_area) 
          SELECT '150-AWT-1001', 'QUALIFY WITH INDIVIDUALLY ASSIGNED WEAPON', 1, 1 FROM DUAL 
UNION ALL SELECT '150-AWT-1002', 'EMPLOY HAND GRENADES', 1, 1 FROM DUAL 
UNION ALL SELECT '150-AWT-1003', 'PERFORM INDIVIDUAL MOVEMENT TECHNIQUES', 1, 2 FROM DUAL 
UNION ALL SELECT '150-AWT-1004', 'NAVIGATE FROM ONE POINT TO ANOTHER', 1, 2 FROM DUAL 
UNION ALL SELECT '150-AWT-1005', 'MOVE UNDER DIRECT FIRE', 1, 2 FROM DUAL 
UNION ALL SELECT '150-AWT-1006', 'PERFORM VOICE COMMUNICATIONS SITREP/SPOTREP/9-LINE MEDEVAC/EXPLOSIVE HAZARD', 1, 3 FROM DUAL 
UNION ALL SELECT '150-AWT-1007', 'USE VISUAL SIGNALING TECHNIQUES', 1, 3 FROM DUAL 
UNION ALL SELECT '150-AWT-1008', 'REACT TO CHEMICAL OR BIOLOGICAL ATTACK/HAZARD', 1, 4 FROM DUAL 
UNION ALL SELECT '150-AWT-1009', 'PERFORM IMMEDIATE LIFESAVING MEASURES', 1, 4 FROM DUAL 
UNION ALL SELECT '150-AWT-1010', 'PERFORM COUNTER IED', 1, 4 FROM DUAL 
UNION ALL SELECT '150-AWT-1011', 'MAINTAIN SITUATIONAL AWARENESS / EVERY SOLDIER IS A SENSOR', 1, 4 FROM DUAL 
UNION ALL SELECT '150-AWT-1012', 'PERFORM COMBATIVES', 1, null FROM DUAL 
UNION ALL SELECT '150-AWT-1013', 'ASSESSS AND RESPOND TO THREATS (ESCALATION OF FORCE)', 1, 5 FROM DUAL 
UNION ALL SELECT '150-AWT-1014', 'ADAPT TO CHANGING OPERATIONAL ENVIRONMENTS', 1, 5 FROM DUAL 
UNION ALL SELECT '150-AWT-1015', 'GROW PROFESSIONALLY AND PERSONALLY (BUILD RESILIENCE)', 1, 5 FROM DUAL 
UNION ALL SELECT '150-AWT-2020', 'INDIVIDUAL CONDUCTS LAWS OF WAR', 2, null FROM DUAL 
UNION ALL SELECT '150-AWT-2021', 'FIRST AID', 2, null FROM DUAL 
UNION ALL SELECT '150-AWT-2022', 'REACT TO CHEMICAL OR BIOLOGICAL ATTACK/HAZARD', 2, null FROM DUAL 
UNION ALL SELECT '150-AWT-2023', 'SURVIVE (COMBAT TECHNIQUES)', 2, null FROM DUAL 
UNION ALL SELECT '150-AWT-2024', 'NAVIGATE', 2, null FROM DUAL 
UNION ALL SELECT '150-AWT-2025', 'COMMUNICATE', 2, null FROM DUAL 
UNION ALL SELECT '150-AWT-2026', 'UNIT OPERATIONS', 2, null FROM DUAL 
UNION ALL SELECT '150-AWT-2027', 'SECURITY AND CONTROL', 2, null FROM DUAL 
UNION ALL SELECT '150-AWT-2028', 'EQUIPMENT CHECKS', 2, null FROM DUAL 
UNION ALL SELECT '150-AWT-2029', 'RISK MANAGEMENT', 2, null FROM DUAL 
UNION ALL SELECT '150-AWT-2030', 'ADMINISTRATION/MANAGEMENT', 2, null FROM DUAL 
UNION ALL SELECT '150-AWT-2031', 'BUILD TEAMWORK', 2, null FROM DUAL 
UNION ALL SELECT '150-AWT-3032', 'FIRST AID', 3, null FROM DUAL 
UNION ALL SELECT '150-AWT-3033', 'CHEMICAL, BIOLOGICAL, RADIOLOGICAL, AND NUCLEAR (CBRN)', 3, null FROM DUAL 
UNION ALL SELECT '150-AWT-3034', 'SURVIVE (COMBAT TECHNIQUES)', 3, null FROM DUAL 
UNION ALL SELECT '150-AWT-3035', 'NAVIGATE', 3, null FROM DUAL 
UNION ALL SELECT '150-AWT-3036', 'DEFENSE MEASURES', 3, null FROM DUAL 
UNION ALL SELECT '150-AWT-3037', 'UNIT OPERATION', 3, null FROM DUAL 
UNION ALL SELECT '150-AWT-3038', 'SECURITY AND CONTROL', 3, null FROM DUAL 
UNION ALL SELECT '150-AWT-3039', 'ENEMY PERSONNEL', 3, null FROM DUAL 
UNION ALL SELECT '150-AWT-3040', 'RISK MANAGEMENT', 3, null FROM DUAL 
UNION ALL SELECT '150-AWT-4041', 'CHEMICAL, BIOLOGICAL, RADIOLOGICAL AND NUCLEAR (CBRN)', 4, null FROM DUAL 
UNION ALL SELECT '150-AWT-4042', 'SURVIVE (COMBAT TECHNIQUES)', 4, null FROM DUAL 
UNION ALL SELECT '150-AWT-4043', 'DEFENSE MEASURES', 4, null FROM DUAL 
UNION ALL SELECT '150-AWT-4044', 'UNIT OPERATIONS', 4, null FROM DUAL 
UNION ALL SELECT '150-AWT-4045', 'SECURITY AND CONTROL', 4, null FROM DUAL 
UNION ALL SELECT '150-AWT-4046', 'CRIME PREVENTION', 4, null FROM DUAL 
UNION ALL SELECT '150-AWT-4047', 'RISK MANAGEMENT', 4, null FROM DUAL 
UNION ALL SELECT '150-AWT-4048', 'ADMINISTRATION/MANAGEMENT', 4, null FROM DUAL ;


SELECT task_number, task_title, skill_level, subject_area FROM atis_awt_tasks;