
DELETE FROM atis_ictl_tasks;


INSERT INTO atis_ictl_tasks (mos_id, task_number, task_title) 
          SELECT '11B', '031-503-3006', 'SUPERVISE RADIATION MONITORING' FROM DUAL 
UNION ALL SELECT '11B', '031-505-4003', 'CONTROL UNIT RADIATION EXPOSURE' FROM DUAL 
UNION ALL SELECT '11B', '052-192-3060', 'CONDUCT A BREACH OF A MINEFIELD' FROM DUAL 
UNION ALL SELECT '11B', '052-703-9107', 'PLAN FOR AN IMPROVISED EXPLOSIVE DEVICE (IED) THREAT IN A COIN ENVIRONMENT (UNCLASSIFIED / FOR OFFICIAL USE ONLY) (U//FOUO)' FROM DUAL 
UNION ALL SELECT '11B', '052-703-9113', 'PLAN FOR THE INTEGRATION OF COUNTER-IMPROVISED EXPLOSIVE DEVICE (C-IED) ASSETS (UNCLASSIFIED//FOR OFFICIAL USE ONLY) (U//FOUO)' FROM DUAL 
UNION ALL SELECT '11B', '071-316-2651', 'RECOMMEND EMPLOYMENT OF THE M41 IMPROVED TARGET ACQUISITION SYSTEM (ITAS)' FROM DUAL 
UNION ALL SELECT '11B', '071-326-0558', 'EMPLOY SNIPER DEFEAT MEASURES' FROM DUAL 
UNION ALL SELECT '11B', '071-326-3003', 'REACT TO AERIAL CONTACT' FROM DUAL 
UNION ALL SELECT '11B', '071-326-5505', 'ISSUE AN OPERATION ORDER (OPORD) AT THE PLATOON LEVEL' FROM DUAL 
UNION ALL SELECT '11B', '071-326-5626', 'PREPARE AN OPERATION ORDER (OPORD) AT THE COMPANY, PLATOON, OR SQUAD LEVEL' FROM DUAL 
UNION ALL SELECT '11B', '071-326-5771', 'PREPARE A SQUAD/SECTION SECTOR SKETCH' FROM DUAL 
UNION ALL SELECT '11B', '071-326-5804', 'CONDUCT A POINT ANTIARMOR AMBUSH BY AN M2 BFV SECTION/SQUAD' FROM DUAL 
UNION ALL SELECT '11B', '071-332-5052', 'CONDUCT ROLES OF THE PLATOON SERGEANT' FROM DUAL 
UNION ALL SELECT '11B', '071-332-5053', 'SUPERVISE MODERN ARMY COMBATIVE PROGRAM AT SQUAD/SECTION LEVEL' FROM DUAL 
UNION ALL SELECT '11B', '071-334-4002', 'ESTABLISH A HELICOPTER LANDING POINT' FROM DUAL 
UNION ALL SELECT '11B', '071-410-0010', 'CONDUCT A LEADER''S RECONNAISSANCE' FROM DUAL 
UNION ALL SELECT '11B', '071-420-0028', 'CONDUCT A SQUAD ATTACK' FROM DUAL 
UNION ALL SELECT '11B', '071-430-0028', 'CONSOLIDATE AND REORGANIZE A UNIT' FROM DUAL 
UNION ALL SELECT '11B', '071-440-0003', 'CONDUCT AN ATTACK ON A BUILDING BY A SQUAD DURING AN URBAN OPERATION' FROM DUAL 
UNION ALL SELECT '11B', '071-440-0006', 'CONDUCT A DEFENSE BY A SQUAD DURING AN URBAN OPERATION' FROM DUAL 
UNION ALL SELECT '11B', '071-440-0014', 'CONDUCT AN ATTACK ON A BUILDING BY AN M2 BFV SECTION/SQUAD DURING AN URBAN OPERATION' FROM DUAL 
UNION ALL SELECT '11B', '071-440-0016', 'CONDUCT A DEFENSE BY A MOUNTED SECTION/SQUAD DURING AN URBAN OPERATION' FROM DUAL 
UNION ALL SELECT '11B', '071-450-0014', 'CONDUCT A POINT ANTIARMOR AMBUSH BY A SQUAD' FROM DUAL 
UNION ALL SELECT '11B', '071-450-0030', 'CONDUCT A PASSAGE OF LINES' FROM DUAL 
UNION ALL SELECT '11B', '071-450-0041', 'CONDUCT A POINT AMBUSH' FROM DUAL 
UNION ALL SELECT '11B', '071-450-0042', 'CONDUCT A POINT ANTIARMOR AMBUSH BY AN ANTIARMOR SECTION' FROM DUAL 
UNION ALL SELECT '11B', '071-630-0001', 'EMPLOY COMMON OPERATIONAL TERMS AND GRAPHICS AT SQUAD LEVEL' FROM DUAL 
UNION ALL SELECT '11B', '071-720-0006', 'ESTABLISH A PATROL BASE OR OBJECTIVE RALLY POINT' FROM DUAL 
UNION ALL SELECT '11B', '171-121-4021', 'PLAN RANGE OPERATIONS' FROM DUAL 
UNION ALL SELECT '11B', '171-121-4022', 'PLAN LIVE FIRE RANGE OPERATIONS' FROM DUAL 
UNION ALL SELECT '11B', '171-121-4023', 'CONDUCT LIVE FIRE RANGE OPERATIONS' FROM DUAL 
UNION ALL SELECT '11B', '171-121-4045', 'CONDUCT TROOP LEADING PROCEDURES' FROM DUAL 
UNION ALL SELECT '11B', '171-123-1300', 'CONDUCT A ROUTE RECONNAISSANCE' FROM DUAL 
UNION ALL SELECT '11B', '171-123-1301', 'CONDUCT AN AREA OR ZONE RECONNAISSANCE' FROM DUAL 
UNION ALL SELECT '11B', '171-123-4013', 'CONDUCT THE RECONNAISSANCE OF AN OBSTACLE' FROM DUAL 
UNION ALL SELECT '11B', '171-134-0009', 'SUPERVISE OPERATOR MAINTENANCE ON THE LONG RANGE ADVANCED SCOUT SURVEILLANCE SYSTEM (LRAS3)' FROM DUAL 
UNION ALL SELECT '11B', '171-134-0010', 'SUPERVISE PREPARATION OF THE LONG RANGE ADVANCED SCOUT SURVEILLANCE SYSTEM (LRAS3) FOR OPERATION IN HMMWV-MOUNTED CONFIGURATION' FROM DUAL 
UNION ALL SELECT '11B', '171-134-0011', 'SUPERVISE PREPARATION OF THE LONG RANGE ADVANCED SCOUT SURVEILLANCE SYSTEM (LRAS3) FOR OPERATION IN DISMOUNTED (TRIPOD) CONFIGURATION' FROM DUAL 
UNION ALL SELECT '11B', '171-134-0012', 'SUPERVISE OPERATION OF THE LONG RANGE ADVANCED SCOUT SURVEILLANCE SYSTEM (LRAS3)' FROM DUAL 
UNION ALL SELECT '11B', '171-134-0013', 'SUPERVISE TROUBLESHOOTING THE LONG RANGE ADVANCED SCOUT SURVEILLANCE SYSTEM (LRAS3)' FROM DUAL 
UNION ALL SELECT '11B', '171-134-0014', 'SUPERVISE REMOVAL OF THE LONG RANGE ADVANCED SCOUT SURVEILLANCE SYSTEM (LRAS3) FROM A HMMWV' FROM DUAL 
UNION ALL SELECT '11B', '171-134-0015', 'SUPERVISE REMOVAL OF THE LONG RANGE ADVANCED SCOUT SURVEILLANCE SYSTEM (LRAS3) FROM A TRIPOD' FROM DUAL 
UNION ALL SELECT '11B', '171-170-0001', 'PREPARE COMBAT MESSAGES USING FORCE XXI BATTLE COMMAND BRIGADE-AND-BELOW / BLUE FORCE TRACKING (FBCB2 / BFT)' FROM DUAL 
UNION ALL SELECT '11B', '171-170-0005', 'APPLY MESSAGE ADDRESSING FEATURES IN FORCE XXI COMMAND BRIGADE-AND-BELOW / BLUE FORCE TRACKING (FBCB2 / BFT)' FROM DUAL 
UNION ALL SELECT '11B', '171-170-0006', 'PERFORM MESSAGE MANAGEMENT USING FORCE XXI COMMAND BRIGADE-AND-BELOW / BLUE FORCE TRACKING (FBCB2 / BFT)' FROM DUAL 
UNION ALL SELECT '11B', '171-170-0007', 'CREATE AN OVERLAY MESSAGE USING FORCE XXI BATTLE COMMAND BRIGADE-AND-BELOW/BLUE FORCE TRACKING (FBCB2/BFT)' FROM DUAL 
UNION ALL SELECT '11B', '171-170-0008', 'PREPARE REPORTS USING FORCE XXI BATTLE COMMAND BRIGADE-AND-BELOW/BLUE FORCE TRACKING (FBCB2/BFT)' FROM DUAL 
UNION ALL SELECT '11B', '171-170-0009', 'PREPARE FIRE/ALERT MESSAGES USING FORCE XXI BATTLE COMMAND BRIGADE-AND-BELOW/BLUE FORCE TRACKING (FBCB2/BFT)' FROM DUAL 
UNION ALL SELECT '11B', '171-170-0010', 'PREPARE ORDER/REQUEST MESSAGES USING FORCE XXI BATTLE COMMAND BRIGADE-AND-BELOW/BLUE FORCE TRACKING (FBCB2/BFT)' FROM DUAL 
UNION ALL SELECT '11B', '171-170-0017', 'EMPLOY MAP FUNCTIONS USING FORCE XXI BATTLE COMMAND BRIGADE-AND-BELOW/BLUE FORCE TRACKING (FBCB2/BFT)' FROM DUAL 
UNION ALL SELECT '11B', '171-170-0018', 'PERFORM PROCEDURES IN REACTION TO AUTHENTICATION AND REMOTE SECURITY LOCKOUT ON FORCE XXI BATTLE COMMAND BRIGADE-AND-BELOW/BLUE FORCE TRACKING (FBCB2/BFT)' FROM DUAL 
UNION ALL SELECT '11B', '171-170-0019', 'EMPLOY FLASH IMMEDIATE PRIORITY ROUTINE (FIPR) MESSAGE PRECEDENCE FUNCTIONS USING FORCE XXI BATTLE COMMAND BRIGADE-AND-BELOW/BLUE FORCE TRACKING (FBCB2/BFT)' FROM DUAL 
UNION ALL SELECT '11B', '171-170-0020', 'EMPLOY STATUS FUNCTIONS USING FORCE XXI BATTLE COMMAND BRIGADE-AND-BELOW/BLUE FORCE TRACKING (FBCB2/BFT)' FROM DUAL 
UNION ALL SELECT '11B', '171-170-0021', 'EMPLOY ADMIN FUNCTIONS USING FORCE XXI BATTLE COMMAND BRIGADE-AND-BELOW/BLUE FORCE TRACKING (FBCB2/BFT)' FROM DUAL 
UNION ALL SELECT '11B', '171-170-0022', 'EMPLOY APPS (APPLICATIONS) FUNCTIONS USING FORCE XXI BATTLE COMMAND BRIGADE-AND-BELOW/BLUE FORCE TRACKING (FBCB2/BFT)' FROM DUAL 
UNION ALL SELECT '11B', '171-170-0023', 'EMPLOY NAVIGATION FUNCTIONS USING FORCE XXI BATTLE COMMAND BRIGADE-AND-BELOW/BLUE FORCE TRACKING (FBCB2 / BFT)' FROM DUAL 
UNION ALL SELECT '11B', '171-170-0024', 'EMPLOY QUICK SEND FUNCTIONS USING FORCE XXI BATTLE COMMAND BRIGADE-AND-BELOW/BLUE FORCE TRACKING (FBCB2/BFT)' FROM DUAL 
UNION ALL SELECT '11B', '171-170-0025', 'EMPLOY FILTER FUNCTIONS USING FORCE XXI BATTLE COMMAND BRIGADE-AND-BELOW/BLUE FORCE TRACKING (FBCB2/BFT)' FROM DUAL 
UNION ALL SELECT '11B', '171-170-0026', 'TROUBLESHOOT FORCE XXI BATTLE COMMAND BRIGADE-AND-BELOW/BLUE FORCE TRACKING (FBCB2/BFT) HARDWARE' FROM DUAL 
UNION ALL SELECT '11B', '171-170-0027', 'TROUBLESHOOT FORCE XXI BATTLE COMMAND BRIGADE-AND-BELOW / BLUE FORCE TRACKING (FBCB2 / BFT) SOFTWARE' FROM DUAL 
UNION ALL SELECT '11B', '171-170-0028', 'PERFORM REMOTE ACCESS SECURITY PROCEDURES USING FORCE XXI BATTLE COMMAND BRIGADE-AND-BELOW / BLUE FORCE TRACKING (FBCB2 / BFT)' FROM DUAL 
UNION ALL SELECT '11B', '171-170-0034', 'TROUBLESHOOT FORCE XXI BATTLE COMMAND BRIGADE-AND-BELOW / ENHANCED POSITION LOCATION REPORTING SYSTEM (FBCB2 / EPLRS) HARDWARE' FROM DUAL 
UNION ALL SELECT '11B', '171-170-0037', 'PERFORM SYSTEM ADMINISTRATIVE FUNCTIONS ON FORCE XXI BATTLE COMMAND BRIGADE-AND-BELOW / BLUE FORCE TRACKING (FBCB2 / BFT)' FROM DUAL 
UNION ALL SELECT '11B', '171-170-0039', 'PERFORM PASSWORD SECURITY PROCEDURES FOR FORCE XXI BATTLE COMMAND BRIGADE-AND-BELOW / BLUE FORCE TRACKING (FBCB2 / BFT)' FROM DUAL 
UNION ALL SELECT '11B', '171-170-0040', 'DETERMINE THE STATUS FUNCTION USING FORCE XXI BATTLE COMMAND BRIGADE-AND-BELOW / ENHANCED POSITION LOCATION REPORTING SYSTEM (FBCB2 / EPLRS)' FROM DUAL 
UNION ALL SELECT '11B', '171-170-0047', 'PERFORM MAP LOADING AND MAP MANAGEMENT PROCEDURES FOR FORCE XXI BATTLE COMMAND BRIGADE-AND-BELOW / BLUE FORCE TRACKING (FBCB2 / BFT)' FROM DUAL 
UNION ALL SELECT '11B', '171-170-0066', 'PREPARE THE FORCE XXI BATTLE COMMAND BRIGADE AND BELOW/BLUE FORCE TRACKING (FBCB2/BFT) TACTICAL OPERATIONS CENTER (TOC) SYSTEM FOR OPERATION' FROM DUAL 
UNION ALL SELECT '11B', '171-300-0009', 'CONDUCT AIR GROUND COORDINATION' FROM DUAL 
UNION ALL SELECT '11B', '171-300-0059', 'EMPLOY SQUAD DESIGNATED MARKSMAN IN A TACTICAL ENVIRONMENT' FROM DUAL 
UNION ALL SELECT '11B', '171-610-0008', 'DISPLAY KNOWLEDGE OF COIN OPERATIONS' FROM DUAL 
UNION ALL SELECT '11B', '551-751-2400', 'CONDUCT HASTY VEHICLE RECOVERY' FROM DUAL ;


SELECT task_number FROM atis_ictl_tasks;
