DELETE FROM atis_mos;
/

INSERT INTO atis_mos (mos_code,  mos_specialty, branch_id, cmf_id, major_duties_desc) 
          SELECT '02B', 'Cornet or Trumpet Player', 'AG', null, 'Participates as a musician in a military band and supervises an instrumental section.' FROM DUAL 
UNION ALL SELECT '02C', 'Baritone or Euphonium Player', 'AG', null, 'Participates as a musician in a military band and supervises an instrumental section.' FROM DUAL 
UNION ALL SELECT '02D', 'French Horn Player', 'AG', null, 'Participates as a musician in a military band and supervises an instrumental section.' FROM DUAL 
UNION ALL SELECT '02E', 'Trombone Player', 'AG', null, 'Participates as a musician in a military band and supervises an instrumental section.' FROM DUAL 
UNION ALL SELECT '02F', 'Tuba Player', 'AG', null, 'Participates as a musician in a military band and supervises an instrumental section.' FROM DUAL 
UNION ALL SELECT '02G', 'Flute or Piccolo Player', 'AG', null, 'Participates as a musician in a military band and supervises an instrumental section.' FROM DUAL 
UNION ALL SELECT '02H', 'Oboe Player', 'AG', null, 'Participates as a musician in a military band and supervises an instrumental section.' FROM DUAL 
UNION ALL SELECT '02J', 'Clarinet Player', 'AG', null, 'Participates as a musician in a military band and supervises an instrumental section.' FROM DUAL 
UNION ALL SELECT '02K', 'Bassoon Player', 'AG', null, 'Participates as a musician in a military band and supervises an instrumental section.' FROM DUAL 
UNION ALL SELECT '02L', 'Saxophone Player', 'AG', null, 'Participates as a musician in a military band and supervises an instrumental section.' FROM DUAL 
UNION ALL SELECT '02M', 'Percussion Player', 'AG', null, 'Participates as a musician in a military band and supervises an instrumental section.' FROM DUAL 
UNION ALL SELECT '02N', 'Keyboard Player', 'AG', null, 'Participates as a musician in a military band and supervises an instrumental section.' FROM DUAL 
UNION ALL SELECT '02T', 'Guitar Player', 'AG', null, 'Participates as a musician in a military band and supervises an instrumental section.' FROM DUAL 
UNION ALL SELECT '02U', 'Electric Bass Guitar Player', 'AG', null, 'Participates as a musician in a military band and supervises an instrumental section.' FROM DUAL 
UNION ALL SELECT '02Z', 'Bands Senior Sergeant', 'AG', null, 'Supervise military musical activities of division, Army, and MACOM bands. Serves as unit First Sergeant or Sergeant Major and enlisted conductor of the band.' FROM DUAL 
UNION ALL SELECT '11B', 'Infantryman', 'IN', '11', 'Supervises, leads, or serves as a member of an infantry activity that employs individual or crew served weapons in support of offensive and defensive combat operations.' FROM DUAL 
UNION ALL SELECT '11C', 'Indirect Fire Infantryman', 'IN', '11', 'Supervise or be a member of a mortar squad, section, or platoon. Employs crew and individual weapons in offensive, defensive, and retrograde ground combat tactical operations.' FROM DUAL 
UNION ALL SELECT '11O', 'Infantry Officer', 'IN', '11', 'An Infantry Officer is to be a leader in operations specific to the Infantry and to lead others in all areas of land combat.' FROM DUAL 
UNION ALL SELECT '11Z', 'Infantry Senior Sergeant', 'IN', '11', 'Serves as principal NCO in the operations section of combined arms or infantry brigades and higher level organizations. Provides tactical and technical guidance and professional support to subordinates and makes recommendations to superiors in the accomplishment of their duties.' FROM DUAL 
UNION ALL SELECT '12O', 'Engineer Officer', 'EN', null, 'An Officer in the Army Corps of Engineers is responsible for providing support in full spectrum of engineer duties. Engineer Officers help the Army in building structures, developing civil works program, working with natural resources as well as providing combat support on the battlefield.' FROM DUAL 
UNION ALL SELECT '131A', 'Field Artillery Targeting Technician', 'FA', '13', 'The Field Artillery Targeting Technician is a warrant officer position which provides information to a commander and his staff about all aspects of the Army''s targeting methodologies and equipment. This officer may also be involve in the planning and execution of operations as well as coordinating those operations across units.' FROM DUAL 
UNION ALL SELECT '13B', 'Cannon Crewmember', 'FA', '13', 'Supervises or serves as a member of field artillery cannon section or ammunition section.' FROM DUAL 
UNION ALL SELECT '13C', 'Tactical Automated Fire Control Systems (TAFCS) Specialist', 'FA', '13', 'Leads, supervises, or serves as a member of an activity operating tactical fire direction TAFCS equipment in a field artillery cannon battalion or higher unit.' FROM DUAL 
UNION ALL SELECT '13D', 'Field Artillery Tactical Data Systems Specialist', 'FA', '13', 'Leads, supervises, or serves as a member of an activity operating FATDS in a Multiple Launch Rocket System (MLRS) battalion, battery, platoon in a field artillery cannon battalion or higher.' FROM DUAL 
UNION ALL SELECT '13E', 'Cannon Fire Direction Specialist', 'FA', '13', 'Leads, supervises, or serves as a member of a fire direction element or operations section of a field artillery cannon unit.' FROM DUAL 
UNION ALL SELECT '13F', 'Fire Support Specialist', 'FA', '13', 'Leads, supervises, or serves as in intelligence activities including target processing in FA cannon battalions, division artillery, artillery, and maneuver brigade and Corps headquarters and Fire Support Elements.' FROM DUAL 
UNION ALL SELECT '13M', 'Multiple Launch Rocket System (MLRS) Crewmember', 'FA', '13', 'Supervises or serves as a member of an MLRS crew or section.' FROM DUAL 
UNION ALL SELECT '13O', 'Field Artillery Officer', 'FA', '13', 'A Field Artillery Officer is to be a leader in operations specific to the Field Artillery Branch and to be an expert in the tactics, techniques and procedures for suppressing the enemy by cannon, rocket and missile fire and to help integrate all fire support assets into combined arms operations.' FROM DUAL 
UNION ALL SELECT '13P', 'Multiple Launch Rocket System (MLRS) Operations/Fire Detection Specialist', 'FA', '13', 'Leads, supervises, or serves as a member of a MLRS fire direction center or firing platoon headquarters.' FROM DUAL 
UNION ALL SELECT '13R', 'Field Artillery Firefinder Radar Operator', 'FA', '13', 'Operates or provides leadership in the operation of FA radar systems.' FROM DUAL 
UNION ALL SELECT '13S', 'Field Artillery Surveyor', 'FA', '13', 'Leads, supervises, or serves as a member in field artillery survey operations.' FROM DUAL 
UNION ALL SELECT '13W', 'Field Artillery Meteorological Crewmember', 'FA', '13', 'Lead, supervise, or participate in the operation of a field artillery meteorological observation station.' FROM DUAL 
UNION ALL SELECT '13Z', 'Field Artillery Senior Sergeant', 'FA', '13', 'Leads in the fire support, operations/intelligence, and target acquisition activities in a field artillery battalion, brigade, division artillery, or corps artillery.' FROM DUAL 
UNION ALL SELECT '14E', 'PATRIOT Fire Control Enhanced Operator and Maintainer', 'ADA', '14', 'Supervise or serve in an air defense unit or as a member of an air defense activity engaged in operations or intelligence functions of liaison units.' FROM DUAL 
UNION ALL SELECT '14J', 'Early Warning System Operator', 'ADA', '14', 'Supervises or serves as a member of a manual early warning network section, team, or platoon in operations and intelligence functions.' FROM DUAL 
UNION ALL SELECT '14O', 'Air Defense Artillery Officer', 'ADA', '14', 'The role of an Air Defense Artillery Officer is to be a leader in operations specific to the Air Defense Artillery Branch and to be an expert in the tactics, techniques and procedures for the employment of air defense systems. You will lead teams in protecting U.S. forces from aerial attack, missile attack and enemy surveillance.' FROM DUAL 
UNION ALL SELECT '14R', 'Bradley Linebacker Crewmember', 'ADA', '14', 'Supervise and operate the BSFV and associated equipment.' FROM DUAL 
UNION ALL SELECT '14S', 'AVENGER Crewmember', 'ADA', '14', 'Supervises, operates or serves as a member of a lightweight, highly mobile, Air Defense weapons system.' FROM DUAL 
UNION ALL SELECT '14Z', 'Air Defense Artillery Senior Sergeant', 'ADA', '14', 'Supervises, plans, coordinates, and directs the emplacement, operation, unit level maintenance and management of air defense artillery weapon systems in support of ADA units at all levels.' FROM DUAL 
UNION ALL SELECT '15B', 'Aircraft Powerplant Repairer', 'AV', '15', 'Supervises, inspect, and perform aviation unit (AVUM), intermediate (AVIM), and depot maintenance on aircraft turbine engines and components.' FROM DUAL 
UNION ALL SELECT '15D', 'Aircraft Powertrain Repairer', 'AV', '15', 'Supervises, inspects, and performs aviation unit (AVUM), intermediate (AVIM), and depot maintenance on aircraft powertrain systems.' FROM DUAL 
UNION ALL SELECT '15F', 'Aircraft Electrician', 'AV', '15', 'Supervise, inspect, and perform aviation unit (AVUM), intermediate (AVIM), and depot electrical maintenance on aircraft electrical systems.' FROM DUAL 
UNION ALL SELECT '15G', 'Aircraft Structural Repairer', 'AV', '15', 'Supervise and perform aviation unit (AVUM), intermediate (AVIM,) and depot maintenance on aircraft structures.' FROM DUAL 
UNION ALL SELECT '15H', 'Aircraft Pneudraulics Repairer', 'AV', '15', 'Supervise, inspect, and perform aviation unit (AVUM), intermediate (AVIM), and depot maintenance on aircraft pneudraulics systems.' FROM DUAL 
UNION ALL SELECT '15J', 'OH-58D Armament, Electrical, Avionics Sytems Repairer', 'AV', '15', 'Supervise, inspect, and perform aviation unit, intermediate, and depot maintenance and repairs on the OH-58D armament, electrical, and avionics systems to include the electrical, electronic, mechanical, and pneudraulics systems associated with those systems.' FROM DUAL 
UNION ALL SELECT '15K', 'Aircraft Components Repair Supervisor', 'AV', '15', 'Supervises aviation unit (AVUM), intermediate (AVIM), and depot maintenance on aircraft components, aviation communications and other electronic/electrical systems associated with Army aircraft. The individual must be knowledgeable of the duties performed by personnel in MOS 15B, 15D, 15F, 15G, 15H, and 15N.' FROM DUAL 
UNION ALL SELECT '15M', 'Utility Helicopter Repairer', 'AV', '15', 'Supervises and performs maintenance on UH-1 helicopters, excluding repair of systems components.' FROM DUAL 
UNION ALL SELECT '15N', 'Avionic Mechanic', 'AV', '15', 'Performs unit and intermediate maintenance on tactical communications security (COM-SEC), communication, navigation, identification friend or foe (IFF), and flight control equipment.' FROM DUAL 
UNION ALL SELECT '15O', 'Aviation Officer', 'AV', '15', 'An Officer within the Aviation Branch is first an expert aviator, but is also responsible for the coordination of Aviation operations from maintenance to control tower operations to tactical field missions. All Aviation Officers lead Soldiers and Aviation units and work with the following Army helicopters; OH-58 Kiowa, UH-60 Black Hawk, CH-47 Chinook, and AH-64 Apache.' FROM DUAL 
UNION ALL SELECT '15P', 'Aviation Operations Specialist', 'AV', '15', 'Schedules and dispatches tactical aircraft missions and performs associated operational administrative duties.' FROM DUAL 
UNION ALL SELECT '15Q', 'Air Traffic Control Operator', 'AV', '15', 'Supervises and provides ATC services, to include flight following using visual flight rules (VFR), instrument flight rules (IFR), and special visual flight rules (SVFR), at ATC facilities.' FROM DUAL 
UNION ALL SELECT '15R', 'AH-64 Attack Helicopter Repairer', 'AV', '15', 'Supervises and performs maintenance on AH-64 attack helicopters, excluding repair of systems components.' FROM DUAL 
UNION ALL SELECT '15S', 'OH-58D Helicopter Repairer', 'AV', '15', 'Supervises and performs maintenance on OH-58D helicopters, excluding repair of systems components.' FROM DUAL 
UNION ALL SELECT '15T', 'UH-60 Helicopter Repairer', 'AV', '15', 'Supervises and performs maintenance on UH-60 helicopters, excluding repair of systems components.' FROM DUAL 
UNION ALL SELECT '15U', 'Medium Helicopter Repairer', 'AV', '15', 'Supervises and performs maintenance on medium helicopters, excluding repair of systems components.' FROM DUAL 
UNION ALL SELECT '15X', 'AH-64A Armament and Electrical System Repairer', 'AV', '15', 'Performs aviation unit (AVUM), intermediate (AVIM), and depot maintenance on the AH-64 electrical and instrument systems and the electrical, electronic, mechanical, and pneudraulics systems associated with AH-64 armament/missile and fire control systems.' FROM DUAL 
UNION ALL SELECT '15Y', 'AH-64D Armament/Electrical/Avionics Repairer', 'AV', '15', 'Supervises, inspects, and performs aviation unit, intermediate, and depot maintenance on the AH-64D armament, electrical, and avionic systems, to include the electrical, electronic, mechanical, and pneudraulics systems associated with AH-64D armament/missile fire control systems.' FROM DUAL 
UNION ALL SELECT '15Z', 'Aircraft Maintenance Senior Sergeant', 'AV', '15', 'Supervises aviation unit maintenance (AVUM), intermediate (AVIM), and depot maintenance in activities having a mix of aircraft maintenance and/or component repair MOS.' FROM DUAL 
UNION ALL SELECT '180W', 'Special Forces Warrant Officer', 'SF', '18', 'Manages all aspects of Special Forces Operations in all operational environments. Supports Joint and Army strategic, operational, and tactical requirements at all levels of execution as concerns mission planning, development, and execution of special operations worldwide. Responsible for the conduct of unconventional warfare, intelligence collection and strategic reconnaissance, collective security, strike operations, and counter terrorism operations. Supports psychological, civil affairs, and deception requirements; and the conduct of other missions, relative to special forces capabilities, as directed.' FROM DUAL 
UNION ALL SELECT '18A', 'Special Forces Officer', 'SF', '18', 'Special Forces are experts in conducting operations that don''t call for conventional military operations. A Special Forces Officer is responsible for what is typically organized as a 12-man team, known as an Operational Detachment Alpha (ODA).' FROM DUAL 
UNION ALL SELECT '18B', 'Special Forces Weapons Sergeant', 'SF', '18', 'Employs conventional and unconventional warfare tactics and techniques in individual and small unit infantry operations.' FROM DUAL 
UNION ALL SELECT '18C', 'Special Forces Engineer Sergeant', 'SF', '18', 'Employs conventional and unconventional warfare tactics and techniques in combat engineering and maintains detachment engineer equipment and supplies.' FROM DUAL 
UNION ALL SELECT '18D', 'Special Forces Medical Sergeant', 'SF', '18', 'Employs conventional and unconventional warfare tactics and techniques in providing medical care and treatment.' FROM DUAL 
UNION ALL SELECT '18E', 'Special Forces Communications Sergeant', 'SF', '18', 'Employs conventional and unconventional warfare tactics and techniques in communications.' FROM DUAL 
UNION ALL SELECT '18F', 'Special Forces Assistant Operations and Intelligence Sergeant', 'SF', '18', 'Employs conventional and unconventional warfare tactics and techniques in intelligence collection and processing. Trains and maintains proficiency in all major duties. Provides tactical and technical guidance to the Detachment Commander, indigenous and allied personnel. Plans, organizes, trains, advises, assists and supervises indigenous and allied personnel on collection and processing of intelligence information. Performs intelligence and operational duties when task organized in preparation (isolation) for special missions and during operations.' FROM DUAL 
UNION ALL SELECT '18O', 'Special Forces Officer', 'SF', '18', 'A Special Forces Officer is responsible for what is typically organized as a 12-man team, known as an Operational Detachment Alpha (ODA).' FROM DUAL 
UNION ALL SELECT '18Z', 'Special Forces Senior Sergeant', 'SF', '18', 'Supervises, instructs, and serves as the senior enlisted member for SF activities. Trains and maintains proficiency in all major duties associated with Special Forces.' FROM DUAL 
UNION ALL SELECT '19D', 'Cavalry Scout', 'AR', '19', 'Leads, serves, or assists as a member of scout crew, squad, section, or platoon in reconnaissance, security, and other combat operations.' FROM DUAL 
UNION ALL SELECT '19K', 'M1 Armor Crewman', 'AR', '19', 'Leads, supervises, or serves as a member of M1 armor unit in offensive and defensive combat operations. In addition, serves or assists on staffs at battalion or higher level.' FROM DUAL 
UNION ALL SELECT '19O', 'Armor Officer', 'AR', '19', 'The role of an Armor Officer is to be a leader in operations specific to the Armor Branch and to lead others in many areas of combat operations. As an Armor Officer, you may either work with tank units that utilize the M1A1 and M1A2 Abrams Tanks, or cavalry units responsible for forward reconnaissance operations.' FROM DUAL 
UNION ALL SELECT '19Z', 'Armor Senior Sergeant', 'AR', '19', 'Serve as principal NCO in armor company, cavalry troop, or operations and intelligence staff sections in armor battalion, cavalry squadron, or higher level organizations.' FROM DUAL 
UNION ALL SELECT '21B', 'Combat Engineer', 'EN', '21', 'Supervise, serve, or assist as a member of a team, squad, section, or platoon; provide combat engineering support to combat forces; and operate Combat Engineer Vehicles (CEV), Armored Vehicle Launched Bridges (AVLB), and Armored Combat Earthmover (ACE).' FROM DUAL 
UNION ALL SELECT '21C', 'Bridge Crewmember', 'EN', '21', 'Command, serve, or assist as a member of a squad, section, or platoon. They provide conventional and powered bridge and rafting support for wet and dry gap crossing operations.' FROM DUAL 
UNION ALL SELECT '21D', 'Diver', 'EN', '21', 'Supervises or performs underwater reconnaissance, demolition, repair, and salvage.' FROM DUAL 
UNION ALL SELECT '21E', 'Heavy Construction Equipment Operator', 'EN', '21', 'Operates crawler and wheeled tractors with dozer attachments, scoop loader, motorized grader, and towed or self-propelled scraper.' FROM DUAL 
UNION ALL SELECT '21F', 'Crane Operator', 'EN', '21', 'Operates crawler and truckmounted cranes and crane shovels.' FROM DUAL 
UNION ALL SELECT '21G', 'Quarrying Specialist', 'EN', '21', 'Supervises or operates electric, pneumatic, and internal combustion powered machines used in drilling, crushing, grading, and cleaning gravel and rock, or detonates explosives to blast rock in quarries and at construction sites.' FROM DUAL 
UNION ALL SELECT '21H', 'Construction Engineering Supervisor', 'EN', '21', 'Supervises construction, repair, and utility services of buildings, warehouses, fixed bridges, port facilities, and petroleum pipelines, tanks, and related equipment.' FROM DUAL 
UNION ALL SELECT '21J', 'General Construction Equipment Operator', 'EN', '21', 'Operates air compressors and special purpose construction machines engaged in compaction, ditching, pumping, and auguring.' FROM DUAL 
UNION ALL SELECT '21K', 'Plumber', 'EN', '21', 'Installs and repairs pipe systems and fixtures, and petroleum pipeline systems.' FROM DUAL 
UNION ALL SELECT '21L', 'Lithographer', 'EN', '21', 'Operates and performs operator maintenance on offset duplicators/presses, copy cameras, plate making, and various types of bindery and film processing equipment. Supervises and performs all printing and binding, camera operations, layout, and plate making activities.' FROM DUAL 
UNION ALL SELECT '21M', 'Firefighter', 'EN', '21', 'Supervises or performs firefighting, rescue, salvage and fire protection operations.' FROM DUAL 
UNION ALL SELECT '21N', 'Construction Equipment Supervisor', 'EN', '21', 'Supervises construction equipment, quarry, paving, and plant equipment operations and crew maintenance of equipment.' FROM DUAL 
UNION ALL SELECT '21P', 'Prime Power Production Specialist', 'EN', '21', 'Supervises, operates, installs, and maintains electric power plant and associated auxiliary systems and equipment.' FROM DUAL 
UNION ALL SELECT '21Q', 'Transmission and Distribution Specialist', 'EN', '21', 'Supervises or installs and maintains electrical distribution systems; performs duties as a member of a transmission and distribution team.' FROM DUAL 
UNION ALL SELECT '21R', 'Interior Electrician', 'EN', '21', 'Supervises or performs installation and maintenance of interior electrical systems and equipment.' FROM DUAL 
UNION ALL SELECT '21S', 'Topographic Surveyor', 'EN', '21', 'Supervises or conducts surveys to provide control data for map making and/or artillery support and supervises or performs topographic or geodetic computations.' FROM DUAL 
UNION ALL SELECT '21T', 'Technical Engineering Specialist', 'EN', '21', 'Supervises or participates in construction site development to include technical investigation, surveying, drafting, development of construction plans and specifications, and performing quality control inspections.' FROM DUAL 
UNION ALL SELECT '21U', 'Topographic Analyst', 'EN', '21', 'Supervises and/or performs cartographic and terrain analysis duties; collects and processes military geographic information from remote sensed imagery, digital data, intelligence data, existing topographic products, and other collateral data sources; edits cartographic and terrain analysis products; advises command and staff officers on topographic operations and special map product planning.' FROM DUAL 
UNION ALL SELECT '21V', 'Concrete and Asphalt Equipment Operator', 'EN', '21', 'Supervises or operates all equipment used in concrete and asphalt production and paving.' FROM DUAL 
UNION ALL SELECT '21W', 'Carpentry and Masonry Specialist', 'EN', '21', 'Performs general heavy carpentry, structural steel, and masonry duties, to include fabrication, erection, maintenance, and repair of rigging devices, trusses, and other structural assemblies.' FROM DUAL 
UNION ALL SELECT '21X', 'General Engineering Supervisor', 'EN', '21', 'Supervises general engineering activities related to all construction and utility operations.' FROM DUAL 
UNION ALL SELECT '21Y', 'Topographic Engineering Supervisor', 'EN', '21', 'Supervises topographic surveying, cartography and photolithography activities.' FROM DUAL 
UNION ALL SELECT '21Z', 'Combat Engineering Senior Sergeant', 'EN', '21', 'Inspects and advises on bridging, rafting, and river crossing operations. Formulates and maintains construction schedules.' FROM DUAL 
UNION ALL SELECT '254A', 'Signals Systems Technician', 'SC', '25', 'Signal Systems Technician is a warrant officer job which is responsible for integrating and supervising Army Battlefield Control Systems, Local Area Networks, radio systems in tactical units, and other Communications Security (COMSEC) facilities. They may also provide technical assistance, implement tactical data distribution and radio systems, and oversee COMSEC accounts.' FROM DUAL 
UNION ALL SELECT '255A', 'Information Systems Technician', 'SC', '25', 'Information Systems Technician is a warrant officer position responsible for managing information systems associated with Automated Information Systems (AIS) and Internet Protocol (IP) Local Area Networks (LAN). They also develop, install, manage and supervise information systems, as well as instruct and advise commanders and their staff on the successful implementation of such systems.' FROM DUAL 
UNION ALL SELECT '25B', 'Information Technologies Specialist', 'SC', '25', 'Supervises, installs, operates, and performs unit level maintenance on multi-functional/multi-user information processing systems, peripheral equipment, and associated devices in mobile and fixed facilities; performs analyst functions; constructs, edits, and tests computer system programs; conducts data system studies and prepares documentation/specifications for proposals; operates and performs Preventive Maintenance Checks and Services (PMCS) on assigned vehicles and power generators.' FROM DUAL 
UNION ALL SELECT '25C', 'Radio Operator - Maintainer', 'SC', '25', 'Supervise, install, operate, and perform preventive maintenance checks and services (PMCS) and unit level maintenance on assigned amplitude modulation (AM) radios, Enhanced Position Locating and Reporting System (EPLRS) net control stations, radio teletypewriter assemblages, and Army Special Operations communications systems, to include COMSEC devices and associated equipment. Operates manual or automated communications systems. Operates and performs PMCS on assigned vehicles and power generators.' FROM DUAL 
UNION ALL SELECT '25D', 'Telecommunications Operator - Maintainer', 'SC', '25', 'Supervises, installs, operates, and performs unit level maintenance on manual and automated telecommunications equipment centrals and associated peripheral devices. Performs Information Service Support Office (ISSO) duties of printing, publications, and records management. Performs COMSEC Custodian functions. Operates and performs Preventive Maintenance Checks and Services (PMCS) on assigned vehicles and power generators.' FROM DUAL 
UNION ALL SELECT '25F', 'Network Switching Systems Operator - Maintainer', 'SC', '25', 'Supervises, installs, operates, and performs systems maintenance on large and small electronic switches, system control centers, node management facilities, associated multiplexing and combat net radio interface (CNRI) equipment, short range line of sight radio systems, communications security (COMSEC) devices, and other equipment associated with network switching operations.' FROM DUAL 
UNION ALL SELECT '25L', 'Cable Systems lnstaller - Maintainer', 'SC', '25', 'Installs, operates, and performs unit level maintenance on cable and wire communications systems, communication security (COMSEC) devices, and associated equipment. Operates and performs Preventive Maintenance Checks and Services (PMCS) on assigned vehicles and power generators.' FROM DUAL 
UNION ALL SELECT '25M', 'Multimedia Illustrator', 'SC', '25', 'Supervises, plans, or operates manual, mechanical, and electronic multimedia imaging equipment to integrate armament delivery recordings and various visual information products to report combat and non-combat Army, Joint, and Combined operations. Creates illustrations, layouts, map overlays, posters, graphs, and charts, in support of battlefield operations, psychological operations, military intelligence, medical, public affairs, and training functions. Performs unit level maintenance on assigned equipment and PMCS on assigned vehicles and generators' FROM DUAL 
UNION ALL SELECT '25N', 'Nodal Network Systems Operator-Maintainer', 'SC', '25', 'The Nodal Network Systems Operator-Maintainer supervises, installs, operates, and performs field level maintenance on IP-based high speed electronic nodal systems; integrated network control centers; network management facilities; associated multiplexing and transit cased subscriber interface equipment; Communications Security (COMSEC) devices; and other equipment associated with network nodal operations. Performs network management functions in support of maintaining, troubleshooting and re-engineering of nodal assets as needed in support of operational requirements.' FROM DUAL 
UNION ALL SELECT '25O', 'Signal Officer', 'SC', '25', 'A Signal Corps Officer, then, must be an expert in planning, installing, integrating, operating and maintaining the Army''s voice, data and information systems, services and resources. Signal Officers must be highly intelligent, forward-thinking and have a complete knowledge of these various technologies.' FROM DUAL 
UNION ALL SELECT '25P', 'Microwave Systems Operator - Maintainer', 'SC', '25', 'Supervises, installs, operates, and maintains microwave communications systems, associated antennas, multiplexing, and COMSEC equipment. Performs engineering quality control and continuity testing of circuits, trunks, links, systems, and facilities.' FROM DUAL 
UNION ALL SELECT '25Q', 'Multichannel Transmission Systems Operator - Maintainer', 'SC', '25', 'Supervise, install, operate, and perform unit level maintenance on multichannel line-of-sight and tropospheric scatter communications systems, communications security (COMSEC) devices, and associated equipment. Operates and performs preventive maintenance checks and services (PMCS) on assigned vehicles. Installs, operates, and performs PMCS on power generators.' FROM DUAL 
UNION ALL SELECT '25S', 'Satellite Communication Systems Operator - Maintainer', 'SC', '25', 'Supervises, installs, operates, and maintains strategic and tactical multi-channel satellite communications ground terminals, systems, networks, communication security (COMSEC) devices, and associated equipment. Operates and performs preventive maintenance checks and services (PMCS) on assigned communications equipment, vehicles, and power generators.' FROM DUAL 
UNION ALL SELECT '25T', 'Satellite/Microwave Systems Chief', 'SC', '25', 'Plans and supervises the configuration, operation, and maintenance of microwave communications and technical control facilities, satellite operations control systems, large satellite earth terminals, and transportable satellite systems. Provides technical advice to commanders on the integration of telecommunications systems and networks for tactical, strategic, and commercial communications activities.' FROM DUAL 
UNION ALL SELECT '25U', 'Signal Support Systems Specialist', 'SC', '25', 'Supervises, installs, employs, maintains, troubleshoots, and assists users with battlefield Signal support systems and terminal devices. Integrates Signal systems and networks. Performs unit level maintenance on authorized Signal equipment and associated electronic devices. Trains and provides technical assistance to users of Signal equipment. Operates and performs prevent maintenance checks and service (PMCS) on assigned vehicles and power generators.' FROM DUAL 
UNION ALL SELECT '25V', 'Combat Documentation and Production Specialist', 'SC', '25', 'Supervises, plans, and operates electronic and film based still, video, and audio acquisition equipment to document combat and non-combat Army, Joint, and Combined operations. Operates broadcast, collection, television production, and distribution equipment. Creates visual information products in support of combat documentation, psychological operations, military intelligence, medical, public affairs, training, and other functions. Performs unit level maintenance on assigned equipment and PMCS on assigned vehicles and generators.' FROM DUAL 
UNION ALL SELECT '25W', 'Telecommunications Operations Chief', 'SC', '25', 'Plans, coordinates, configures, directs, integrates, and supervises the installation, operation, maintenance, and management of telecommunications systems and networks. Oversees information systems support functions for command, control, communications, and computers (C4) used at all echelons of the Army. The Telecommunications Operations Chief serves in Signal and other special communications activities.' FROM DUAL 
UNION ALL SELECT '25X', 'Senior Signal Sergeant', 'SC', '25', 'Plans, develops, coordinates, directs, and supervises the installation, operation and management of integrated C2 telecommunications and information management networks. Writes Command and Control Communications policy. Provides technical advice and assistance to commanders, staff, and subordinate units. Coordinates Signal activities with higher, lower and adjacent headquarters.' FROM DUAL 
UNION ALL SELECT '25Y', 'Information Systems Chief', 'SC', '25', 'Supervises, plans coordinates and directs the employment, operation, management, and unit level maintenance of multi-functional/multi-user information processing systems in mobile and fixed facilities. Provides technical and tactical advice to command and staff concerning all aspects of information processing system operations, maintenance, and logistical support. Supervises installation, operation, strapping, re-strapping, PMCS and unit level maintenance on COMSEC devices.' FROM DUAL 
UNION ALL SELECT '25Z', 'Visual Information Operations Chief', 'SC', '25', 'Plans, programs, and supervises personnel performing visual information support for Army, Joint, and Combined operations. Manages documentation/production, multimedia illustration, television production and distribution, and VI equipment repair operations and facilities supporting combat documentation, psychological operations, military intelligence, public affairs, training, and special functions. Supervises PMCS on assigned vehicles and power generators.' FROM DUAL 
UNION ALL SELECT '27D', 'Paralegal Specialist', 'AG', '27', 'Paralegal specialists administer and supervise the provision of paralegal services to unit commanders and staff and assist judge advocates/attorneys in providing professional paralegal services in diverse paralegal disciplines, including: organizational paralegal services (military justice, paralegal assistance, claims, administrative law, international law, operational law, and contract law); defense paralegal services; and judicial paralegal services.' FROM DUAL 
UNION ALL SELECT '27E', 'Land Combat Electronic Missile System Repairer', 'OC', '27', 'Supervises or performs direct and general support (DS/GS) level maintenance on the TOW and DRAGON missile systems and the Bradley Fighting Vehicle System (BFVS).' FROM DUAL 
UNION ALL SELECT '27G', 'CHAPARRAL and REDEYE Repairer', 'OC', '27', 'Supervises or performs direct and general support (DS/GS) level maintenance on the CHAPARRAL and REDEYE missile systems and associated equipment and trainers.' FROM DUAL 
UNION ALL SELECT '27M', 'Multiple Launch Rocket System (MLRS) Repairer', 'OC', '27', 'Supervises or performs direct and general support (DS/GS) level maintenance on multiple launch rocket system (MLRS) self-propelled launcher-loader (SPLL) (less carrier), launcher pod/container (LP/C) trainer, and test support group.' FROM DUAL 
UNION ALL SELECT '27O', 'Jag Corps Attorney', 'AG', '27', 'As an Officer in the JAGC and a practicing attorney, your responsibilities will cover everything affecting military operations, focusing on the following areas: criminal law, legal assistance, civil and administrative law, labor and employment law, international and operational law, and contract and fiscal law.' FROM DUAL 
UNION ALL SELECT '27T', 'AVENGER System Repairer', 'OC', '27', 'Supervises, performs, and inspects unit level, direct support, and general support maintenance on AVENGER system and associated components (less carrier and communications).' FROM DUAL 
UNION ALL SELECT '29E', 'Electronic Warfare Specialist', 'MI', '29', 'The Electronic Warfare Specialist supervises and performs military action involving the use of electromagnetic energy to determine, exploit, reduce, or prevent hostile use of the electromagnetic spectrum.' FROM DUAL 
UNION ALL SELECT '30AO', 'Information Operations Officer', 'FAA', '30', 'The Information Operations Officer is responsible for coordinating, planning and integrating both offensive and defensive Information Operations to gain information superiority in support of the commander''s operational concept. Information Operations is integral to every phase of Army and joint planning and operations by linking operational security, psychological operations, deception, electronic warfare, and physical destruction with civil and public affairs capabilities.' FROM DUAL 
UNION ALL SELECT '31B', 'Military Police', 'MP', '31', 'Supervise or provide support to the battlefield by conducting battlefield circulation control, area security, prisoner of war operations, civilian internee operations, law and order operations on the battlefield, and support to the peacetime Army community through security of critical Army resources, crime prevention programs, and preservation of law and order.' FROM DUAL 
UNION ALL SELECT '31D', 'Criminal Investigation Special Agent', 'MP', '31', 'Supervises or conducts investigations of incidents and offenses or allegations of criminality affecting DA or DOD personnel, property, facilities, or activities.' FROM DUAL 
UNION ALL SELECT '31E', 'Corrections Specialist', 'MP', '31', 'Controls, supervises, and counsels military prisoners and manages confinement operations and correctional treatment programs.' FROM DUAL 
UNION ALL SELECT '31O', 'Military Police Officer', 'MP', '31', 'As a Military Police Officer you will be charged with leading soldiers in the execution of offensive operations, defensive operations, stability operations, and civil support operations.' FROM DUAL 
UNION ALL SELECT '350F', 'All Source Intelligence Technician', 'MI', '35', 'The All Source Intelligence Technician is a warrant officer position which is responsible for combining and organizing intelligence information from different source into a single finished product. They may also advise the commander and his staff on the intelligence situation and considerations, as well as coordinating with analytical groups, specialized intelligence activities, and intergovernmental or multinational organizations.' FROM DUAL 
UNION ALL SELECT '350G', 'Imagery Intelligence Technician', 'MI', '35', 'Imagery Intelligence Technician is a warrant officer position that is responsible for providing expertise and leadership in geographic intelligence (GEOINT). They may act as the officer in charge of a team performing imagery analysis on a variety of still or video images, such as satellites and other national-level assets, unmanned aerial vehicles (UAV), or cockpit video from an aircraft. In addition to identifying terrain, equipment, movement and any other potential threats, they may also perform intelligence briefings of the information they uncover.' FROM DUAL 
UNION ALL SELECT '351L', 'Counter Intelligence Technician', 'MI', '35', 'The Counter Intelligence Technician is a warrant officer position which conducts investigations into potential acts of terrorism, espionage, or sabotage, against the Army, and works to prevent such acts. They also report such threats to commanders and their staff, and may also work with the Criminal Investigation Division, FBI, Department of Justice, and other federal or state agencies.' FROM DUAL 
UNION ALL SELECT '351M', 'Human Intelligence Collection Technician', 'MI', '35', 'Human Intelligence Collection Technician (HUMINT Collection Technician) is a warrant officer position which is responsible for the gathering of intelligence from human sources. HUMINT Technicians interrogate and debrief (as per Uniform Code of Military Justice, and other applicable regulations and agreements) personnel, as well developing plans for effective interrogation and constructing and delivering reports based on their findings.' FROM DUAL 
UNION ALL SELECT '352P', 'Voice Interception Technician', 'MI', '35', 'Voice Interception Technician is a warrant officer position which is responsible for conducting and directing Intelligence and Electronic Warfare (IEW) personnel on correct techniques, procedures, and employment of IEW assets. In addition, they may also advise commanders and their staff on the most effective way to employ IEW assets.' FROM DUAL 
UNION ALL SELECT '35F', 'Intelligence Analyst', 'MI', '35', 'Supervises, performs, or coordinates, collection management, analysis, processing, and dissemination of strategic and tactical intelligence.' FROM DUAL 
UNION ALL SELECT '35G', 'Imagery Analyst', 'MI', '35', 'Supervises or analyzes aerial and ground permanent record imagery developed by photographic and electronic means. Plans and recommends the use of imaging sensors for reconnaissance and surveillance missions.' FROM DUAL 
UNION ALL SELECT '35H', 'Common Ground Station Operator', 'MI', '35', 'Supervises or participates in detecting, locating and tracking ground targets and rotary wing and slow moving fixed wing aircraft.' FROM DUAL 
UNION ALL SELECT '35L', 'Counterintelligence Agent', 'MI', '35', 'Supervises and conducts, or assists in conducting, CI surveys and investigations of individuals, organizations, and installations to detect, identify, assess, counter, exploit, and neutralize threats to national security.' FROM DUAL 
UNION ALL SELECT '35M', 'Human Intelligence Collector', 'MI', '35', 'Supervises and conducts tactical HUMINT collection operations that include, but are not limited to, debriefings, interrogations, and elicitations in English and foreign languages for positive intelligence and force protection information; screens Human Intelligence (HUMINT) sources and documents to establish priorities for exploitation; under CI supervision, plans and participates in counterintelligence and Force Protection Operations (CFSO).' FROM DUAL 
UNION ALL SELECT '35N', 'Signals Intelligence Analyist', 'MI', '35', 'The Signals Intelligence Analyst supervises and performs analysis and reporting of intercepted foreign communications and non-communications at all echelons. Assist in the Intelligence, Surveillance, and Reconnaissance (ISR) Synchronization process. Produces combat, strategic, and tactical intelligence reports.' FROM DUAL 
UNION ALL SELECT '35O', 'Military Intelligence Officer', 'MI', '35', 'Military Intelligence Officers are always out front, providing essential intelligence and in many cases saving Soldiers who are fighting on the front lines.' FROM DUAL 
UNION ALL SELECT '35P', 'Cryptologic Communications', 'MI', '35', 'The cryptologic linguist performs and supervises detection, acquisition, geolocation, identification, and exploitation and analysis of foreign communications at all echelons using signals intelligence/electronic warfare (SIGINT/EW) systems. The cryptologic linguist copies, translates, transcribes, gists and/or produces summaries of foreign communication transmissions; performs analysis and ISR synchronization to support mission requirements.' FROM DUAL 
UNION ALL SELECT '35T', 'Military Intelligence Systems Maintainer/Integrator', 'MI', '35', 'Supervises or performs unit, direct support, and general support and depot maintenance of Command/Control subsystems, receiver subsystems, and processing/storage subsystems and related equipment at fixed station, remote sites, and US Army depots.' FROM DUAL 
UNION ALL SELECT '36B', 'Financial Management Technician', 'FI', '36', 'The finance management technician performs duties specific to the following financial management processes: budgeting, disbursing, and accounting for government funds; payment for travel and commercial vendor services; pay support of Soldiers and foreign national employees; and internal control operations.' FROM DUAL 
UNION ALL SELECT '37F', 'Psychological Operations Specialist', 'PO', '37', 'Coordinates, supervises, and participates in analysis, planning, production, and dissemination of strategic, tactical, and consolidation PSYOP.' FROM DUAL 
UNION ALL SELECT '38B', 'Civil Affairs Specialist', 'CA', '38', 'Supervises, researches, coordinates, conducts, and participates in analysis, planning, and production of Civil Affairs related documents and actions encompassing both strategic and tactical Civil Affairs operations for Army, joint, and combined military commands.' FROM DUAL 
UNION ALL SELECT '38O', 'Civil Affairs Officer', 'CA', '38', 'Civil Affairs Officers are experts in acting as a liaison between the Army and civilian authorities and populations. Civil Affairs Officers many times must facilitate relationships between U.S. military forces and the people of the nation(s) in which those forces are operating.' FROM DUAL 
UNION ALL SELECT '39B', 'Automatic Test Equipment Operator and Maintainer', 'OC', '39', 'Operates, maintains, and supervises unit and direct and general support (DS/GS) level maintenance on Automatic Test Equipment (ATE) consisting of electronic equipment test and repair facilities.' FROM DUAL 
UNION ALL SELECT '420A', 'Human Resources Technician', 'AG', '42', 'Human Resources Technician is a warrant officer position which supports the Army''s Human Resources/Personnel Management systems through a variety of functions. They perform duties such as: preparing correspondence to both civilian and military organizations, monitor office documents (word processing, spreadsheets, etc), monitors personnel strength and casualties, counsels individuals on personal, financial, and career matters, supervises administrative personnel, and many other vital duties.' FROM DUAL 
UNION ALL SELECT '42A', 'Human Resources Specialist', 'AG', '42', 'The human resources specialist supervises or performs personnel and administrative functions in support of company, battery, and troop; detachments at division, corps, and echelons above corps; in brigade and battalion S1''s or in other similar organizations, activities and units; and advises the commander, the staff, and unit Soldiers on human resource matters. The human resources specialist also participates in occupational classification and management of human resources or supervises personnel management of human resources or supervises personnel management activities to include maintaining officer and enlisted personnel records and processing personnel actions concerning soldiers and their families.' FROM DUAL 
UNION ALL SELECT '42BO', 'Human Resources Officer', 'AG', '42', 'As an Adjutant General Officer, you will be responsible for providing personnel support that affect Soldiers’ overall welfare and well being, while assisting commanders by accounting for and keeping Soldiers combat-ready.' FROM DUAL 
UNION ALL SELECT '42HO', 'Senior Human Resources Officer', 'AG', '42', 'The duties of a Senior Human Resources Officer are much the same as the duties of a Human Resources Officer, but MOS 42HO is for officers of the rank Major or above.' FROM DUAL 
UNION ALL SELECT '42S', 'Special Band Member', 'AG', '42', 'Performs as a musician or in direct support of the mission of The U.S. Army Band, U.S. Army Field Band, U.S. Military Academy Band, or the 3rd Infantry (The Old Guard) Fife and Drum Corps.' FROM DUAL 
UNION ALL SELECT '44B', 'Metal Worker', 'OC', '44', 'Supervises, inspects, installs, modifies, and performs maintenance on metal body components, radiators, fuel tanks, hulls, and accessories of Army watercraft and amphibians.' FROM DUAL 
UNION ALL SELECT '44E', 'Machinist', 'OC', '63', 'Supervises and performs the fabrication, repair, and modifications of metallic and nonmetallic parts and supervises metalworking shop activities.' FROM DUAL 
UNION ALL SELECT '45B', 'Small Arms/Artillery Repairer', 'OC', '63', 'Performs direct support and general support (DS/GS) maintenance and repairs on small arms, other infantry weapons, and towed artillery.' FROM DUAL 
UNION ALL SELECT '45D', 'Self-propelled Field Artillery Turret Mechanic', 'OC', '45', 'Performs unit maintenance of carriage-mounted armament, associated fire control, and related systems on all self-propelled field artillery weapon systems.' FROM DUAL 
UNION ALL SELECT '45G', 'Fire Control System Repairer', 'OC', '45', 'Supervises and performs direct and general support (DS/GS) maintenance on combat vehicle, infantry and artillery fire control systems and equipment, and related test equipment.' FROM DUAL 
UNION ALL SELECT '45K', 'Armament Repairer', 'OC', '45', 'Supervises and performs direct/general support (DS/GS) and depot level maintenance/repairs on the mechanisms/systems of tank turrets/weapons, fighting vehicles, towed/self-propelled artillery, small arms, and other infantry weapons.' FROM DUAL 
UNION ALL SELECT '46Q', 'Public Affairs Specialist', 'AG', '46', 'Participates in and assists with the supervision of the administration of Army public affairs programs, primarily through writing and photographing the Army’s activities, for use in the internal and external news media.' FROM DUAL 
UNION ALL SELECT '46R', 'Broadcast Journalist', 'AG', '46', 'Participates in or supervises the operation of radio or television broadcast section, team, detachment, or Armed Forces Radio and Television Service network affiliate or comparable broadcast activity.' FROM DUAL 
UNION ALL SELECT '46Z', 'Public Affairs Chief', 'AG', '46', 'Supervise radio and television broadcasting, Army command information, and public affairs programs. Must be able to supervise personnel performing the duties of MOS 46Q and 46R at skill “5” and below.' FROM DUAL 
UNION ALL SELECT '52C', 'Utilities Equipment Repairer', 'OC', '52', 'Supervises and performs unit, direct support, and general support (DS/GS) maintenance to include utilities equipment and special purpose support systems.' FROM DUAL 
UNION ALL SELECT '52D', 'Power-Generation Equipment Repairer', 'OC', '52', 'Supervises and performs unit, direct support, and general support (DS/GS) maintenance functions, including overhaul, but not rebuild of power generation equipment, internal combustion engines, and associated equipment up through 200KW (except for turbine engine driven generators).' FROM DUAL 
UNION ALL SELECT '52F', 'Turbine Engine Driven Generator Repairer', 'OC', '52', 'Performs and supervises unit, direct support, and general support (DS/GS) maintenance functions, including overhaul (but not rebuild) of turbine engine driven tactical generator sets, turbine engine prime mover of tactical generator set and associated equipment.' FROM DUAL 
UNION ALL SELECT '52X', 'Special Purpose Equipment Repairer', 'OC', '52', 'Supervises the performance of unit, direct support and general support (DS/GS) special purpose equipment maintenance activities. Performs maintenance management activities, including production and quality control.' FROM DUAL 
UNION ALL SELECT '53AO', 'Systems Automation Management Officer', 'FAA', '53', 'A Systems Automation Management Officer supervises information processing units as well as the installation and activities of those units. They also advise a commander and his staff on effective automation policy and implementation. In addition, they also formulate procedures for contingency operation during system emergencies, outages, or maintenance downtime.' FROM DUAL 
UNION ALL SELECT '56M', 'Chaplain Assistant', 'AG', '56', 'Provides specified elements of religious support mission in deployments, combat operations, training, and sustainment.' FROM DUAL 
UNION ALL SELECT '56O', 'Chaplain', 'AG', '56', 'As an Army chaplain you will have the responsibility of caring for the spiritual well-being of Soldiers and their Families. An Army chaplain's flock can consist of over 1,500 people. For this reason, the Army chaplain is crucial to the success of the Army's mission. Providing spiritual leadership for the Army Family requires a special person with a unique calling.' FROM DUAL 
UNION ALL SELECT '57AO', 'Simulations Operations Officer', 'FAA', '57', 'Simulations Operations Officers are tasked with planning and employing simulations systems in support of training, and combat rehearsal. They may also be responsible for developing doctrine and equipment for the FA57 operations, developing and operating the simulation technology, and assist with simulation systems development.' FROM DUAL 
UNION ALL SELECT '57E', 'Laundry and Shower Specialist', 'QM', '57', 'Supervises or performs laundry, shower, delousing, personnel and clothing decontamination, and re-impregnation functions.' FROM DUAL 
UNION ALL SELECT '61NO', 'Flight Surgeon', 'FAA', '61', 'A Flight Surgeon serves as the liaison between the medical and aviation commands, and has both clinical and non-clinical duties. The clinical duties involve providing primary medical care to all aviation and support personnel, as well as reviewing medical care provided by others and reviewing its impact on the flight status upon an individual, and performing aeromedical and in-flight evaluations. The non-clinical duties involve providing 24-hour on call service, establishing procedures for grounding of crewmen, monitoring the physical and mental health of all aviation personnel, and participate in Flying Evaluation Board (FEB) to determine if personnel are able to perform aviation duties.' FROM DUAL 
UNION ALL SELECT '62O', 'Medical Corps Officer', 'FAA', '62', 'As a Medical Service Corps officer, you will be responsible for providing health care to soldiers, their families and others eligible to receive this care in the military community. During combat, the Medical Corps Officer oversees the emergency medical management of casualties and makes sure Soldiers are combat ready when it comes to their overall health.' FROM DUAL 
UNION ALL SELECT '63A', 'M1 ABRAMS Systems Maintainer', 'OC', '63', 'Supervises and performs unit maintenance and select on-board direct support tasks i.e., major assembly replacement on M1 tanks to include the turret and fire control.' FROM DUAL 
UNION ALL SELECT '63B', 'Light-Wheel Vehicle Mechanic', 'OC', '63', 'Supervises and performs unit maintenance and recovery operations on gasoline and diesel fueled light-wheel vehicles (prime movers designated as 5 ton or less and their associated trailers) and associated items. Supervises unit maintenance and recovery operations on track and heavy-wheel vehicles, and on material handling equipment (MHE).' FROM DUAL 
UNION ALL SELECT '63D', 'Artillery Mechanic', 'OC', '63', 'Supervises and performs unit maintenance and recovery of all self-propelled field artillery cannon weapon systems, including the automotive, turret, fire control, and chemical protection subsystems thereof.' FROM DUAL 
UNION ALL SELECT '63G', 'Fuel and Electrical Systems Repairer', 'OC', '63', 'Performs direct support and general support (DS/GS) maintenance on fuel and electrical systems of wheel and track vehicles, brake system components, and on internal combustion engines associated with power generation equipment or material handling equipment.' FROM DUAL 
UNION ALL SELECT '63H', 'Track Vehicle Repairer', 'OC', '63', 'Supervises and performs direct support and general support (DS/GS) maintenance on track vehicles; supervises maintenance on wheeled vehicles, material handling equipment (MHE), and chemical quartermaster equipment (less office machines); and supervises related activities including fuel and electrical system repair and maintenance.' FROM DUAL 
UNION ALL SELECT '63J', 'Quartermaster and Chemical Equipment Repairer', 'OC', '63', 'Supervises or performs unit and direct support and general support (DS/GS) maintenance on chemical equipment, quartermaster machinery, forced air-heaters, and special purpose equipment.' FROM DUAL 
UNION ALL SELECT '63M', 'M2/3 Bradley Fighting Vehicle System Maintainer', 'OC', '63', 'Supervises and performs unit maintenance and select on-board direct support task i.e., major assembly and LRU replacement on the M2/M3 A1/A2 series Bradley fighting vehicle, M6 Linebacker, and M7 Bradley Fighting Infantry Support Team (hull and turret).' FROM DUAL 
UNION ALL SELECT '63O', 'Dental Corps Officer', 'FAA', '63', 'A Dental Corps officer is responsible for providing health care to soldiers, their families and others eligible to receive this care in the military community. During combat, the Dental Corps Officer assists in the emergency medical management of casualties; identifies casualties through dental records and makes sure Soldiers are combat ready when it comes to their health.' FROM DUAL 
UNION ALL SELECT '63S', 'Heavy-Wheel Vehicle Mechanic', 'OC', '63', 'Performs unit maintenance on heavy-wheel vehicles (prime movers designated as more than 5 tons and their associated trailers) and material handling equipment (MHE).' FROM DUAL 
UNION ALL SELECT '63W', 'Wheel Vehicle Repairer', 'OC', '63', 'Performs direct support and general support (DS/GS) maintenance on wheel vehicles, material handling equipment (MHE) (less propulsion motor on electrical MHE), trailers, and associated items.' FROM DUAL 
UNION ALL SELECT '63Y', 'Track Vehicle Mechanic', 'OC', '63', 'Performs unit maintenance on track vehicles in other than self-propelled field artillery, armored, mechanized infantry, and armored cavalry units.' FROM DUAL 
UNION ALL SELECT '63Z', 'Mechanical Maintenance Supervisor', 'OC', '63', 'Supervises, plans, coordinates, and directs the unit, direct support and general support (DS/GS) maintenance of all mechanical equipment.' FROM DUAL 
UNION ALL SELECT '64O', 'Veterinary Corps Officer', 'VC', '64', 'Veterinary Corps officers are responsible for treating government-owned animals and the valued pets of service members and their families. Army Veterinary Corps Officers are also responsible for programs ensuring the safety and security of Department of Defense food supplies, both here and abroad.' FROM DUAL 
UNION ALL SELECT '65O', 'Medical Specialist Corps Officer', 'FAA', '65', 'Medical Specialist Corps Officers are essential in treating and helping the overall health of Soldiers and their families. From medical fields such as occupational therapy and physical therapy to dietician and physician assistant, the Army Medical Specialist Corps includes four areas of specialty:' FROM DUAL 
UNION ALL SELECT '66O', 'Nurse Corps Officer', 'FAA', '66', 's an Officer in the Army Nurse Corps, you will lead a nursing team in caring for Soldiers and their families. You will be responsible for and address all aspects of patient care, including initiating and coordinating multidisciplinary care. You''ll also identify and organize resources for patients and their families to help with inpatient, outpatient and home care.' FROM DUAL 
UNION ALL SELECT '67O', 'Medical Service Corps Officer', 'FAA', '67', 'Medical Service Corps Officers are essential in treating and helping the overall health of Soldiers and their families. They are also responsible for much of the medical research that takes place in the Army.' FROM DUAL 
UNION ALL SELECT '68A', 'Biomedical Equipment Specialist', 'FAA', '68', 'Performs maintenance services and repairs of all medical equipment. This equipment employs mechanical, hydraulic, pneumatic, compressed gas and steam, electrical/electronic, solid state, digital, microprocessor, optical, and radiological principles.' FROM DUAL 
UNION ALL SELECT '68D', 'Operating Room Specialist', 'FAA', '68', 'Assists the nursing staff in preparing the patient and the operating room (OR) environment for surgery and for providing assistance to the medical staff during surgical procedures. They also operate the centralized material service (CMS) and are responsible for preparing and maintaining sterile medical supplies and special equipment for medical treatment facilities. The operating room specialist also assists in the management of OR suites.' FROM DUAL 
UNION ALL SELECT '68E', 'Dental Specialist', 'FAA', '68', 'Assists the dental officer in prevention, examination, and treatment of diseases of teeth and oral region, or assists with the management of dental treatment facilities.' FROM DUAL 
UNION ALL SELECT '68G', 'Patient Administration Specialist', 'FAA', '68', 'Supervises or performs administrative duties in patient administration division of hospital or other medical activity.' FROM DUAL 
UNION ALL SELECT '68H', 'Optical Laboratory Specialist', 'FAA', '68', 'Assembles spectacles utilizing presurfaced single-vision lenses; surfaces multi-vision lens and assembles multi-vision spectacles; repairs and fabricates spectacles and supervises optical laboratory personnel.' FROM DUAL 
UNION ALL SELECT '68J', 'Medical Logistics Specialist', 'FAA', '68', 'Performs or supervises requisitioning, receipt, inventory management, storage, preservation, issue, salvage, destruction stock control, quality control, property management, repair parts management, inspection, packing and shipping, care, segregation, and accounting of medical supplies and equipment.' FROM DUAL 
UNION ALL SELECT '68K', 'Medical Laboratory Specialist', 'FAA', '68', 'Performs blood-banking procedures and elementary and advanced examinations of biological and environmental specimens to aid in the diagnosis, treatment, and prevention of disease and other medical disorders.' FROM DUAL 
UNION ALL SELECT '68M', 'Hospital Food Service Specialist', 'FAA', '68', 'Assists in the supervision of medical nutrition care operations, or plans, prepares, cooks, and serves food for regular and modified diets in field and fixed hospitals.' FROM DUAL 
UNION ALL SELECT '68P', 'Radiology Specialist', 'FAA', '68', 'Operates fixed and portable radiology equipment or supervises radiology activities.' FROM DUAL 
UNION ALL SELECT '68Q', 'Pharmacy Specialist', 'FAA', '68', 'Prepares, controls, and issues pharmaceutical products under the supervision of a pharmacist or physician, or supervises pharmacy activities.' FROM DUAL 
UNION ALL SELECT '68R', 'Veterinary Food Inspection Specialist', 'FAA', '68', 'Supervises the inspection of, or inspects, meat, poultry, water foods, eggs, dairy products, operational rations, fresh fruits, and vegetables in depots, supply points, and on military installations to assure a safe, high quality food supply for DoD personnel in all environments with emphasis on the field wartime environment.' FROM DUAL 
UNION ALL SELECT '68S', 'Preventive Medicine Specialist', 'FAA', '68', 'Conducts or assists with preventive medicine inspections, surveys, control operations, and preventive medicine laboratory procedures, supervises preventive medicine facilities, or serves on preventive medicine staff.' FROM DUAL 
UNION ALL SELECT '68T', 'Animal Care Specialist', 'FAA', '68', 'Supervises or provides the care, management, treatment, and sanitary conditions for animals, with a primary responsibility of prevention and control of diseases transmitted from animal to man and comprehensive care for government owned animals.' FROM DUAL 
UNION ALL SELECT '68V', 'Respiratory Specialist', 'FAA', '68', 'Assists with the management of a respiratory unit or administers respiratory therapy and performs pulmonary function tests under the supervision of a physician or nurse anesthetist.' FROM DUAL 
UNION ALL SELECT '68W', 'Health Care Specialist', 'MC', '68', 'Provides emergency medical treatment, limited primary care, force health protection, and evacuation in a variety of operational and clinical settings from point of injury or illness through the continuum of military health care.' FROM DUAL 
UNION ALL SELECT '68X', 'Mental Health Specialist', 'FAA', '68', 'Under the supervision of a psychiatrist, social worker, psychiatric nurse, or psychologist, assists with the management and treatment in/out-patient mental health activities during peace time or mobilization; collects and records psychosocial and physical data; counsels and treats clients/ patients with personal, behavioral, or mental health problems.' FROM DUAL 
UNION ALL SELECT '70H', 'Medical Operations Officer', 'FAA', '70', 'A Medical Operations Officer plans and directs the activities of personnel and units responsible for inventory management of all Class VIII medical supplies. The Medical Operations Officer also directs and exercises staff supervision of units engaged in production, acquisition, storage, and distribution of medical equipment, repair parts, and supplies. The Medical Operations Officer also serves as an advisor to commanders and their staffs on the subject of supporting Health Services operations.' FROM DUAL 
UNION ALL SELECT '73BO', 'Clinical Psychologist', 'FAA', '73', 'As a clinical psychologist in the Army, you will promote effective mental health in our collaborative health care environment. As a clinical psychologist and an Officer on the U.S. Army Health Care Team, you''ll have the opportunity to work with soldiers and their families - in a variety of settings.' FROM DUAL 
UNION ALL SELECT '74D', 'Chemical Operations Specialist', 'CM', '74', 'Operates, performs operator maintenance, or supervises the use of NBC detection and decontamination equipment, smoke generators, and assists in the establishment, administration, training, and application of NBC defense measures. The NBC NCO provides training, advice, and supervision regarding the proper use and maintenance procedures for chemical equipment and chemical operations in company and higher level organizations.' FROM DUAL 
UNION ALL SELECT '74O', 'Chemical, Biological, Radiological and Nuclear (CBRN) Officer', 'CM', '74', 'CBRN Officers command or serve as a Platoon Leader of a Chemical unit while employing the state-of-the-art CBRN defense systems. In a command and staff role the CBRN Officer, plans, coordinates, and directs CBRN operations and training within a command or activity to include CBRN vulnerability assessment; multi-spectral obscuration; sensitive site exploitation and assessment; CBRN reconnaissance; CBRN decontamination; CBRN force protection; and combating WMD, which includes nonproliferation, counter proliferation, and consequence management.' FROM DUAL 
UNION ALL SELECT '79R', 'Recruiter NCO', 'AG', '79', 'Recruits qualified personnel for entry into the Army in accordance with applicable regulations, supervises recruiting and recruiting support activities.' FROM DUAL 
UNION ALL SELECT '79S', 'Retention NCO', 'AG', '79', 'Counsels and/or reenlist or extends qualified soldiers in the Army and supervises retention activities' FROM DUAL 
UNION ALL SELECT '79T', 'Recruiting and Retention NCO', 'AG', '79', 'Recruits and retains qualified soldiers for entry into the Army National Guard in accordance with applicable regulations. Supervises recruiting and retention activities.' FROM DUAL 
UNION ALL SELECT '882A', 'Mobility Officer', 'TC', '88', 'The Mobility Officer is a warrant officer position which is responsible for planning and executing unit movement and distribution operations. They may also prepare both deployment and redeployment plans, conduct training in unit movement operations, and advise commanders and their staff in conducting unit movement operations.' FROM DUAL 
UNION ALL SELECT '88H', 'Cargo Specialist', 'TC', '88', 'Transfers or supervises the transfer of passengers and cargo to and from air, land, and water transport by manual and mechanical methods.' FROM DUAL 
UNION ALL SELECT '88K', 'Watercraft Operator', 'TC', '88', 'Performs mariner duties and supervises other personnel on Army watercraft and amphibians.' FROM DUAL 
UNION ALL SELECT '88L', 'Watercraft Engineer', 'TC', '88', 'Supervises or performs unit, direct support (DS), and general support (GS) maintenance. Services Army watercraft, amphibians and auxiliary equipment on marine vessels.' FROM DUAL 
UNION ALL SELECT '88M', 'Motor Transport Operator', 'TC', '88', 'Supervises or operates wheel vehicles to transport personnel and cargo.' FROM DUAL 
UNION ALL SELECT '88N', 'Transportation Management Coordinator', 'TC', '88', 'Coordinates, monitors, controls and supervises the movement of personnel, equipment, and cargo by air, rail, highway, and water. Determines the most efficient mode of transport that accomplishes mission requirements.' FROM DUAL 
UNION ALL SELECT '88O', 'Transportation Officer', 'TC', '88', 'Transportation Officers are responsible for moving supplies, troops and equipment anywhere on the globe. During war, the Transportation personnel utilizes trucks, boats and airplanes to provide extremely fast support to the combat teams on the front lines.' FROM DUAL 
UNION ALL SELECT '88Z', 'Transportation Senior Sergeant', 'TC', '88', 'Supervises the operation and control of movement for personnel and cargo by air, rail, motor transport, and water.' FROM DUAL 
UNION ALL SELECT '890A', 'Ammunition Technician', 'OC', '89', 'Ammunition Technician is a warrant officer position which is responsible for receipt, storage, issue, and demilitarization of conventional ammunition and all its components. This position may also be responsible for investigation ammunition accidents and malfunctions, as well as preparing contingency plans for ammunition storage and security.' FROM DUAL 
UNION ALL SELECT '89B', 'Ammunition Specialist', 'OC', '89', 'Receives, stores, and issues conventional ammunition, guided missiles, large rockets, and other ammunition related items; performs maintenance (unit, direct support and general support) modification, destruction, and demilitarization on ammunition and explosive components; and operates computer hardware and software/utilities manual records to perform stock control and accounting procedures.' FROM DUAL 
UNION ALL SELECT '89D', 'Explosive Ordnance Disposal Specialist', 'OC', '89', 'Locates, identifies, renders safe, and disposes of foreign and domestic conventional, chemical, or nuclear ordnance and improvised explosive devices (IED); supports VIP missions for the US Secret Service, State Department, and other Federal agencies.' FROM DUAL 
UNION ALL SELECT '90AO', 'Logistics Officer', 'FAA', '90', 'A Logistics Officer keeps a unit moving. They are responsible for planning, developing, and directing the logistical operations of a unit. This position also requires the officer to have experience in integrating the functions of supply, transportation, maintenance, aviation logistics, and medical service into a cohesive unit.' FROM DUAL 
UNION ALL SELECT '915A', 'Automotive Maintenance Warrant Officer', 'OC', '91', 'Automotive Maintenance is a warrant officer position which plans and performs field maintenance on wheeled and light tracked vehicles, as well as self-propelled artillery systems, ground support, and other powered equipment. As well as fixing malfunctioning equipment, they are also responsible for shop safety, inventory, writing and maintaining Standard Operating Procedures (SOPs), scheduling routine maintenance, and managing the dispatch of available vehicles.' FROM DUAL 
UNION ALL SELECT '91E', 'Allied Trades Specialist (Machinist)', 'OC', '91', 'The machinist supervises and performs the fabrication, repair, and modifications of metallic and nonmetallic parts and supervises metalworking shop activities.' FROM DUAL 
UNION ALL SELECT '91L', 'Construction Equipment Repairer', 'OC', '91', 'Supervises and performs unit, direct support and general support (DS/GS) maintenance on construction equipment which includes that used for earth-moving, grading, and compaction; lifting and loading; quarrying and rock crushing; asphalt and concrete mixing and surfacing; water pumping; air compression and pneumatic tools; and powered bridging.' FROM DUAL 
UNION ALL SELECT '91O', 'Ordnance Officer', 'OC', '91', 'Ordnance Officers are responsible for ensuring that all weapons systems, vehicles, and equipment are ready and available--and in perfect working order--at all times. An Ordnance Officer will also manage the developing, testing, fielding, handling, storage and disposal of munitions.' FROM DUAL 
UNION ALL SELECT '920A', 'Property Accounting Technician', 'QM', '92', 'Property Accounting Technician is a warrant officer position responsible for property accountability, all requisitions are valid, and locating standard and non-standard supplies and equipment through military and other channels. They are also responsible for preventing fraud and waste, providing input into annual budget, and monitoring supply chains to ensure compliance with Army and other policies.' FROM DUAL 
UNION ALL SELECT '920B', 'Supply Systems Technician', 'QM', '92', 'Supply Systems Technician is a warrant officer position which is responsible for supervising personnel on supply systems policy and procedures. They are also responsible for managing the receipt, storage, and issue of equipment, inspecting supported units for supply performance standards, providing technical guidance, and conducting periodic inventories of items.' FROM DUAL 
UNION ALL SELECT '920B', 'Supply Systems Technician', 'QM', '92', 'Supply Systems Technician is a warrant officer position which is responsible for supervising personnel on supply systems policy and procedures. They are also responsible for managing the receipt, storage, and issue of equipment, inspecting supported units for supply performance standards, providing technical guidance, and conducting periodic inventories of items.' FROM DUAL 
UNION ALL SELECT '921A', 'Airdrop Systems Technician', 'QM', '92', 'Airdrop Systems Technician is a warrant officer position which is responsible for providing commanders and their staff with guidance on conducting or receiving airborne or airdrop operations. They are also responsible for supervising the inspection and packing of parachutes, removing unservicable parachutes from inventory, and supervise maintenance of airdrop equipment.' FROM DUAL 
UNION ALL SELECT '92A', 'Automated Logistical Specialist', 'QM', '92', 'Supervises and performs management or stock record/warehouse functions pertaining to receipt, storage, distribution, and issue. Maintains equipment records and parts.' FROM DUAL 
UNION ALL SELECT '92F', 'Petroleum Supply Specialist', 'QM', '92', 'Supervises or receives, stores, accounts for, cares for, dispenses, issues, and ships bulk or packaged petroleum, oils, and lubricants (POL) products.' FROM DUAL 
UNION ALL SELECT '92G', 'Food Service Specialist', 'QM', '92', 'Supervises or prepares, cooks, and serves food in field or garrison food service operations.' FROM DUAL 
UNION ALL SELECT '92L', 'Petroleum Laboratory Specialist', 'QM', '92', 'Supervises or conducts laboratory tests on petroleum, oils, and lubricants (POL) products.' FROM DUAL 
UNION ALL SELECT '92M', 'Mortuary Affairs Specialist', 'QM', '92', 'Performs or supervises duties relating to deceased personnel to include recovery, collection, evacuation, establishment of tentative identification, escort, and temporary burial. They also inventory, safeguard, and evacuate personal effects of deceased personnel.' FROM DUAL 
UNION ALL SELECT '92O', 'Quartermaster Officer', 'QM', '92', 'Quartermaster Officers are responsible for making sure equipment, materials and systems are available and functioning for soldiers and their mission.' FROM DUAL 
UNION ALL SELECT '92R', 'Parachute Rigger', 'QM', '92', 'Supervises or packs and repairs cargo and personnel parachutes, and rigs equipment and supply containers for airdrop.' FROM DUAL 
UNION ALL SELECT '92S', 'Fabric Repair Specialist', 'QM', '92', 'Repairs and supervises repair of textile and canvas items, webbed equipment, and clothing.' FROM DUAL 
UNION ALL SELECT '92W', 'Water Treatment Specialist', 'QM', '92', 'Supervises or performs installation and operation of water purification equipment, water storage, and water distribution operations and activities.' FROM DUAL 
UNION ALL SELECT '92Y', 'Unit Supply Specialist', 'QM', '92', 'Supervises or performs duties involving requests, receipt, storage, issue, accountability, and preservation of individual, organizational, installation, and expendable supplies and equipment.' FROM DUAL 
UNION ALL SELECT '92Z', 'Senior Noncommissioned Logistician', 'QM', '92', 'Supervises soldiers engaged in supply, services, material management, and logistics operations.' FROM DUAL 
UNION ALL SELECT '94A', 'Land Combat Electrician', 'OC', '94', 'Supervises, operates, and performs unit and direct support and general support (DS/GS) level maintenance on Land Combat Support Systems.' FROM DUAL 
UNION ALL SELECT '94D', 'Air Traffic Control Equipment Repairer', 'OC', '94', 'Performs unit through intermediate direct support maintenance and installation of ATC communications, navigation aids (NAVAIDS), and landing systems.' FROM DUAL 
UNION ALL SELECT '94E', 'Radio and Communications Security Repairer', 'OC', '94', 'Performs or supervises direct and general support (DS/GS) level maintenance of radio receivers, transmitters, COM-SEC equipment, controlled cryptographic items (CCI), and other associated equipment.' FROM DUAL 
UNION ALL SELECT '94F', 'Special Electronic Devices Repairer', 'OC', '94', 'Performs or supervises direct and general support (DS/GS) level maintenance and repair on special electronic devices, including: night vision equipment, mine detectors, scattering systems, electronic distance and azimuth orienting devices, battlefield illumination devices, electronic azimuth determining devices, and nuclear, biological, and chemical (NBC) warning and measuring devices.' FROM DUAL 
UNION ALL SELECT '94H', 'Test, Measurement, and Diagnostic Equipment Support Specialist', 'OC', '94', 'Performs and supervises duties involving the calibration and repair of general purpose TMDE, selected special purpose TMDE, calibration standards, and accessories. Operates TMDE and calibration standards. Operates and performs preventive maintenance and checks and services (PMCS) on assigned vehicles. Installs, operates, and performs PMCS on power generators.' FROM DUAL 
UNION ALL SELECT '94J', 'Telecommunication Terminal Device Repairer', 'OC', '94', 'Performs or supervises direct and general support (DS/GS) level maintenance of microcomputers and electro-mechanical telecommunications terminal equipment, facsimile machines, Field Artillery (FA) digital devices, and other associated equipment and devices.' FROM DUAL 
UNION ALL SELECT '94L', 'Avionic Communications Equipment Repairer', 'OC', '94', 'Performs intermediate and depot maintenance on aircraft communications equipment.' FROM DUAL 
UNION ALL SELECT '94M', 'Radar Repairer', 'OC', '94', 'Performs or supervises unit, direct, and general support (DS/GS) level maintenance on Ground Based Sensor (GBS) and FIREFINDER radar electronic assemblies and associated equipment.' FROM DUAL 
UNION ALL SELECT '94N', 'Wire Systems Equipment Repairer', 'OC', '94', 'Performs or supervises direct and general support (DS/GS) level maintenance on manual and semiautomatic unit level switchboards, telephones, and associated wire instruments and equipment.' FROM DUAL 
UNION ALL SELECT '94R', 'Avionic Radar Repairer', 'OC', '94', 'Performs intermediate (AVIM) and depot maintenance on avionic equipment which operates using radar principles.' FROM DUAL 
UNION ALL SELECT '94S', 'PATRIOT System Repairer', 'OC', '94', 'Performs or supervises direct and general support (DS/GS) level maintenance on the PATRIOT missile system, associated equipment and trainers.' FROM DUAL 
UNION ALL SELECT '94W', 'Electronic Maintenance Chief', 'OC', '94', 'Supervises, monitors, and directs the electronics maintenance mission of the US Army, and oversees and performs direct and general support (DS/GS) level maintenance of all Army standard electronics equipment, systems, and associated devices, to include communications security (COMSEC) and controlled cryptographic items (CCI) devices.' FROM DUAL 
UNION ALL SELECT '94Y', 'Integrated Family of Test Equipment Operator and Maintainer', 'OC', '94', 'Operates, performs, and supervises unit, direct support, and general support (DS/GS) level maintenance on the Base Shop Test Facility (BSTF), AN/TSM–191. Performs DS/ GS level electronic maintenance, adjustments, tests, fault isolation, and repairs of supported system line replaceable units (LRU), shop replaceable units (SRU), and test program sets (TPS). Operates and performs preventive maintenance checks and services (PMCS) on assigned vehicles and power generators.' FROM DUAL 
UNION ALL SELECT '94Z', 'Senior Electronic Maintenance Chief', 'OC', '94', 'Plans and directs electronic maintenance operations at all levels of command and echelons of the US Army.' FROM DUAL 
UNION ALL SELECT '96R', 'Ground Surveillance Systems Operator', 'MI', '96', 'Supervises or operates ground surveillance systems engaged in intelligence and information gathering.' FROM DUAL 
UNION ALL SELECT '96U', 'Tactical Unmanned Aerial Vehicle Operator', 'MI', '96', 'Supervises or operates the TUAV, to include mission planning, mission sensor/payload operations, launching, remotely piloting, and recovering the aerial vehicle.' FROM DUAL 
UNION ALL SELECT '96Z', 'Intelligence Senior Sergeant', 'MI', '96', 'Supervises intelligence surveillance, collection, analysis, processing, and distribution activities at group, division, corps, US Army, and comparable or higher echelons.' FROM DUAL 
UNION ALL SELECT '97Z', 'Counterintelligence / Human Intelligence Senior Sergeant', 'MI', '97', 'Supervises the collection, processing, development, and dissemination of counterintelligence, counter-signals intelligence, and human intelligence information.' FROM DUAL 
UNION ALL SELECT '98C', 'Signals Intelligence Analyst', 'MI', '98', 'Supervises and performs analysis and reporting of intercepted foreign communications at corps, division and echelon above corps (EAC). Performs collection management. Produces combat, strategic, and tactical intelligence reports.' FROM DUAL 
UNION ALL SELECT '98G', 'Cryptologic Linguist', 'MI', '98', 'Performs and supervises detection, acquisition, location, identification, and exploitation of foreign communications at all echelons using signals equipment. Translates, transcribes, gists, or produces summaries of foreign language transmissions in English/target languages. Performs collection management.' FROM DUAL 
UNION ALL SELECT '98H', 'Communications Locator/Interceptor', 'MI', '98', 'Performs and supervises detection, acquisition, identification, exploitation and location of foreign communications employing international Morse code (IMC) and radio-printer (non-Morse) using signals intelligence/electronic warfare (SIGINT/EW) collection and location equipment. Performs collection management.' FROM DUAL 
UNION ALL SELECT '98J', 'Electronic Intelligence Interceptor/Analyst', 'MI', '98', 'Performs and supervises detection, acquisition, location, identification, exploitation, and reporting of foreign ELINT at division, corps, and echelon above corps (EAC). Performs collection management.' FROM DUAL 
UNION ALL SELECT '98K', 'Signals Collection/Identification Analyst', 'MI', '98', 'Performs and supervises collection, identification, exploitation, and analysis of foreign radioteletype, facsimile, and data communications. Performs collection management.' FROM DUAL 
UNION ALL SELECT '98Z', 'Signals Intelligence Senior Sergeant', 'MI', '98', 'Serves as staff NCO for major commands engaged in Signals intelligence/electronic warfare (SIGINT/EW) operations and combat development or training.' FROM DUAL 
/

SELECT mos_code FROM atis_mos ORDER BY mos_code; 
