DROP TABLE PFSAWH.GB_PFSA_SYSTEM_DIM

/*--*----|----*----|----*----|----*----|---- TEAM ITSS ----|----*----|----*----|----*----|----*---*/
--
--         NAME: GB_PFSA_SYSTEM_DIM
--      PURPOSE: A major grouping End Items. 
--
-- TABLE SOURCE: GB_PFSA_SYSTEM_DIM.sql
--
--   CREATED BY: Gene Belford
-- CREATED DATE: 9 NOVEMBER 2007
--
--  ASSUMPTIONS:
--
--  LIMITATIONS:
--
--        NOTES:
--
/*--*----|----*----|----*----|----*----|----*----|----*----|----*----|----*----|----*----|----*---*/
--
--
CREATE TABLE PFSAWH.GB_PFSA_SYSTEM_DIM
(
	SYSTEM_ID				INTEGER				NOT NULL,
 	LIN						VARCHAR2(6 BYTE), 						-- LINE ITEM NUMBER
	ARMY_TYPE_DESIGNATOR	VARCHAR2(21 BYTE),						-- 'Model number'
 	END_ITEM_NOMEN			VARCHAR2(35 BYTE),
	GEN_NOMEN				VARCHAR2(64 BYTE),
--
 	FSC						VARCHAR2(4 BYTE),						-- FEDERAL SUPPLY CLASSIFICATION  
	NSN						VARCHAR2(13 BYTE),						-- National Stock Number
 	NIIN					VARCHAR2(9 BYTE)	NOT NULL,			-- NATIONAL ITEM IDENTIFICATION NUMBER
 	EIC_DESC				VARCHAR2(3 BYTE),						-- END ITEM CODE 
 	ECC_DESC				VARCHAR2(2 BYTE),						-- EQUIPMENT CATEGORY CODE
	MATCAT_DESC				VARCHAR2(5 BYTE),						-- MATERIEL CATEGORY STRUCTURE CODE
 	MAT_CAT_CD_2_DESC		VARCHAR2(1 BYTE),
 	MAT_CAT_CD_4_5_DESC		VARCHAR2(2 BYTE),
	CAGE_DESC				VARCHAR2(5 BYTE),						-- COMMERCIAL AND GOVERNMENT ENTITY
	UID1_DESC				VARCHAR2(15 BYTE),						-- Unique IDentification Construct 1
	UID2_DESC				VARCHAR2(19 BYTE),						-- Unique IDentification Construct 2
	TYPE_CLASS_CD_DESC		VARCHAR2(1 BYTE),						--
--
	ANAL_VIEW				VARCHAR2(40 BYTE)	NOT NULL,
 	TYPE_ANAL_VIEW			VARCHAR2(20 BYTE),
	SLXN_GROUPING			VARCHAR2(24 BYTE)	NOT NULL,
	SLXN_SUB_GROUPING		VARCHAR2(35 BYTE)	NOT NULL,
--	
	FLEET_TYPE_DESC			VARCHAR2(40 BYTE),
	FLEET_SUBTYPE_DESC		VARCHAR2(40 BYTE),
	FLEET_CAPABILITY_DESC	VARCHAR2(40 BYTE),
--
	RICC_ITM_FL				VARCHAR2(1 BYTE),						-- REPORTABLE ITEM CONTROL CODE
	CBM_SENSOR_FL			VARCHAR2(1 BYTE),						-- Condition Based Maintenance Flag 
--
 	AIRCRAFT				VARCHAR2(1 BYTE),
 	SUPPLY_CLASS_DESC		VARCHAR2(2 BYTE),
 	CL_OF_SUPPLY_CD_DESC	VARCHAR2(1 BYTE),
 	SUBCLASS_OF_SUPPLY_CD_DESC	VARCHAR2(1 BYTE),
--
	STATUS					VARCHAR2(1 BYTE),
	LST_UPDT				DATE				DEFAULT	sysdate ,
	UPDT_BY					VARCHAR2(20 BYTE)	DEFAULT	user ,
--
	active_Fl				CHAR(1)				DEFAULT	'N' ,
	active_Dt				DATE				DEFAULT	'01-JAN-1900' ,
	inactive_Dt				DATE				DEFAULT	'31-DEC-2100'  ,
--
	insert_By				VARCHAR2(30)		DEFAULT	user ,
	insert_Dt				DATE				DEFAULT	sysdate ,
	delete_Fl				CHAR(1)				NULL ,
	delete_Dt				DATE				NULL ,
	hidden_Fl				CHAR(1)				NULL ,
	hidden_Dt				DATE				NULL 
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX PK_GB_PFSA_SYSTEM_DIM ON GB_PFSA_SYSTEM_DIM
(SYSTEM_ID)
LOGGING
NOPARALLEL;

CREATE UNIQUE INDEX IX_GB_PFSA_SYSTEM_DIM ON GB_PFSA_SYSTEM_DIM
(SYSTEM_DESC, SYSTEM_TYPE_DESC, SYSTEM_SUBTYPE_DESC)
LOGGING
NOPARALLEL;

CREATE UNIQUE INDEX JJ_SYSTEM_END_ITEM_DIM_EI_NIIN ON JJ_SYSTEM_END_ITEM_DIM
(SLXN_GROUPING, SLXN_SUB_GROUPING, ANAL_VIEW, END_ITEM_NIIN)
LOGGING
NOPARALLEL;

ALTER TABLE JJ_SYSTEM_END_ITEM_DIM ADD (
  CONSTRAINT PK_JJ_SYSTEM_END_ITEM_DIM
 PRIMARY KEY
 (SYSTEM_END_ITEM_ID));

CREATE UNIQUE INDEX PK_JJ_SYSTEM_END_ITEM_DIM ON JJ_SYSTEM_END_ITEM_DIM
(SYSTEM_END_ITEM_ID)
LOGGING
NOPARALLEL;

-- constraints 

alter table PFSAWH.GB_PFSA_SYSTEM_DIM  add constraint CK_DIM_FLT_TYP_DSC 
	check (SYSTEM_TYPE_DESC='AVIATION' or SYSTEM_TYPE_DESC='COMMUNICATIONS' or SYSTEM_TYPE_DESC='ELECTRONICS' 
		or SYSTEM_TYPE_DESC='GROUND' or SYSTEM_TYPE_DESC='WATER' or SYSTEM_TYPE_DESC='NOT APPLICABLE');

ALTER TABLE PFSAWH.GB_PFSA_SYSTEM_DIM  ADD CONSTRAINT CK_DIM_FLT_SBTYP_DSC 
	CHECK (SYSTEM_SUBTYPE_DESC='AIRCRAFT' OR SYSTEM_SUBTYPE_DESC='HELICOPTER' OR SYSTEM_SUBTYPE_DESC='TRACKED' 
		OR SYSTEM_SUBTYPE_DESC='WHEELED' OR SYSTEM_SUBTYPE_DESC='NOT APPLICABLE');
		
ALTER TABLE PFSAWH.GB_PFSA_SYSTEM_DIM  DROP CONSTRAINT CK_DIM_FLT_CAPAB_DSC		

ALTER TABLE PFSAWH.GB_PFSA_SYSTEM_DIM  ADD CONSTRAINT CK_DIM_FLT_CAPAB_DSC 
	CHECK (SYSTEM_CAPABILITY_DESC='CARGO' OR SYSTEM_CAPABILITY_DESC='UTILITY' OR SYSTEM_CAPABILITY_DESC='ATTACK' 
		OR SYSTEM_CAPABILITY_DESC='CAVALRY' OR SYSTEM_CAPABILITY_DESC='INFANTRY' OR SYSTEM_CAPABILITY_DESC='FIRE SUPPORT'
		OR SYSTEM_CAPABILITY_DESC='SCOUT' OR SYSTEM_CAPABILITY_DESC='NOT APPLICABLE'
		);

-- trigger 

CREATE OR REPLACE TRIGGER TR_I_JJ_SYS_END_ITEM_DIM
BEFORE INSERT
ON PFSAWH.JJ_SYSTEM_END_ITEM_DIM
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
v_system_dim_id NUMBER;
--
--
/******************** TEAM ITSS ************************************************


       NAME:    TR_I_JJ_SYS_END_ITEM_DIM

    PURPOSE:    To perform work as each row is inserted or updated.

   
ASSUMPTIONS:

LIMITATIONS:

      NOTES:


  Date     ECP #            Author           Description
---------  ---------------  ---------------  ---------------------------------
08/27/2007 					  Julie Jamison    Trigger Created
*/


begin
   v_system_dim_id := 0;

   select jj_system_end_item_seq.nextval into v_system_dim_id from dual;
   :new.system_end_item_id := v_system_dim_id;
   :new.last_update := sysdate;
   :new.update_by  := user;

   exception
     when others then
       -- consider logging the error and then re-raise
       raise;
	   
end TR_I_JJ_SYS_END_ITEM_DIM;
/
SHOW ERRORS;

/*----- comments -----*/

COMMENT ON COLUMN GB_PFSA_SYSTEM_DIM.SYSTEM_ID IS 'A major grouping End Items.';

COMMENT ON COLUMN GB_PFSA_SYSTEM_DIM.SYSTEM_DESC IS '';

COMMENT ON COLUMN GB_PFSA_SYSTEM_DIM.SYSTEM_TYPE_DESC IS '';

COMMENT ON COLUMN GB_PFSA_SYSTEM_DIM.SYSTEM_SUBTYPE_DESC IS '';

COMMENT ON COLUMN GB_PFSA_SYSTEM_DIM.SYSTEM_CAPABILITY_DESC IS '';


COMMENT ON COLUMN GB_PFSA_SYSTEM_DIM.STATUS IS 'The date/timestamp of when the record was created/updated.';

COMMENT ON COLUMN GB_PFSA_SYSTEM_DIM.LST_UPDT IS 'The date/timestamp of when the record was created/updated.';

COMMENT ON COLUMN GB_PFSA_SYSTEM_DIM.UPDT_BY IS 'Indicates either the program name or user ID of the person who updated the record.';

INSERT INTO PFSAWH.GB_PFSA_SYSTEM_DIM (SYSTEM_ID, SYSTEM_DESC, SYSTEM_TYPE_DESC, SYSTEM_SUBTYPE_DESC, SYSTEM_CAPABILITY_DESC) 
	VALUES (1, 'CHINOOK', 'AVIATION', 'HELICOPTER', 'CARGO') 
	
SELECT * 
FROM	PFSAWH.GB_PFSA_SYSTEM_DIM
