DROP TABLE PFSAWH.GB_PFSA_FLEET_DIM

/*--*----|----*----|----*----|----*----|---- TEAM ITSS ----|----*----|----*----|----*----|----*---*/
--
--         NAME: GB_PFSA_FLEET_DIM
--      PURPOSE: A major grouping End Items. 
--
-- TABLE SOURCE: GB_PFSA_FLEET_DIM.sql
--
--   CREATED BY: Gene Belford
-- CREATED DATE: 8 NOVEMBER 2007
--
--  ASSUMPTIONS:
--
--  LIMITATIONS:
--
--        NOTES:
--
/*--*----|----*----|----*----|----*----|----*----|----*----|----*----|----*----|----*----|----*---*/
--
--
CREATE TABLE PFSAWH.GB_PFSA_FLEET_DIM
(
	FLEET_ID				NUMBER,
	FLEET_DESC				VARCHAR2(40 BYTE),
	FLEET_TYPE_DESC			VARCHAR2(40 BYTE),
	FLEET_SUBTYPE_DESC		VARCHAR2(40 BYTE),
	FLEET_CAPABILITY_DESC	VARCHAR2(40 BYTE),
--
	STATUS					VARCHAR2(1 BYTE),
	LST_UPDT				DATE				DEFAULT	sysdate ,
	UPDT_BY					VARCHAR2(20 BYTE)	DEFAULT	user ,
--
	active_Fl				CHAR(1)				DEFAULT	'N' ,
	active_Dt				DATE				DEFAULT	'01-JAN-1900' ,
	inactive_Dt				DATE				DEFAULT	'31-DEC-2100'  ,
--
	insert_By				VARCHAR2(30)		DEFAULT	user ,
	insert_Dt				DATE				DEFAULT	sysdate ,
	delete_Fl				CHAR(1)				NULL ,
	delete_Dt				DATE				NULL ,
	hidden_Fl				CHAR(1)				NULL ,
	hidden_Dt				DATE				NULL 
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX PK_GB_PFSA_FLEET_DIM ON GB_PFSA_FLEET_DIM
(FLEET_ID)
LOGGING
NOPARALLEL;

CREATE UNIQUE INDEX IX_GB_PFSA_FLEET_DIM ON GB_PFSA_FLEET_DIM
(FLEET_DESC, FLEET_TYPE_DESC, FLEET_SUBTYPE_DESC)
LOGGING
NOPARALLEL;

-- constraints 

alter table PFSAWH.GB_PFSA_FLEET_DIM  add constraint CK_DIM_FLT_TYP_DSC 
	check (FLEET_TYPE_DESC='AVIATION' or FLEET_TYPE_DESC='COMMUNICATIONS' or FLEET_TYPE_DESC='ELECTRONICS' 
		or FLEET_TYPE_DESC='GROUND' or FLEET_TYPE_DESC='WATER' or FLEET_TYPE_DESC='NOT APPLICABLE');

ALTER TABLE PFSAWH.GB_PFSA_FLEET_DIM  ADD CONSTRAINT CK_DIM_FLT_SBTYP_DSC 
	CHECK (FLEET_SUBTYPE_DESC='AIRCRAFT' OR FLEET_SUBTYPE_DESC='HELICOPTER' OR FLEET_SUBTYPE_DESC='TRACKED' 
		OR FLEET_SUBTYPE_DESC='WHEELED' OR FLEET_SUBTYPE_DESC='NOT APPLICABLE');
		
ALTER TABLE PFSAWH.GB_PFSA_FLEET_DIM  DROP CONSTRAINT CK_DIM_FLT_CAPAB_DSC		

ALTER TABLE PFSAWH.GB_PFSA_FLEET_DIM  ADD CONSTRAINT CK_DIM_FLT_CAPAB_DSC 
	CHECK (FLEET_CAPABILITY_DESC='CARGO' OR FLEET_CAPABILITY_DESC='UTILITY' OR FLEET_CAPABILITY_DESC='ATTACK' 
		OR FLEET_CAPABILITY_DESC='CAVALRY' OR FLEET_CAPABILITY_DESC='INFANTRY' OR FLEET_CAPABILITY_DESC='FIRE SUPPORT'
		OR FLEET_CAPABILITY_DESC='SCOUT' OR FLEET_CAPABILITY_DESC='NOT APPLICABLE'
		);

-- trigger 

CREATE OR REPLACE TRIGGER TR_I_SET_GB_PFSA_FLEET_DIM_ID
BEFORE INSERT
ON PFSAWH.GB_PFSA_FLEET_DIM
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
fleet_id NUMBER;

COMMENT ON COLUMN GB_PFSA_FLEET_DIM.FLEET_ID IS 'PFSA_FLEET_DIM - A major grouping End Items.';

COMMENT ON COLUMN GB_PFSA_FLEET_DIM.FLEET_DESC IS '';

COMMENT ON COLUMN GB_PFSA_FLEET_DIM.FLEET_TYPE_DESC IS '';

COMMENT ON COLUMN GB_PFSA_FLEET_DIM.FLEET_SUBTYPE_DESC IS '';

COMMENT ON COLUMN GB_PFSA_FLEET_DIM.FLEET_CAPABILITY_DESC IS '';


COMMENT ON COLUMN GB_PFSA_FLEET_DIM.STATUS IS 'The status of the record in question.';

COMMENT ON COLUMN GB_PFSA_FLEET_DIM.LST_UPDT IS 'The date/timestamp of when the record was created/updated.';

COMMENT ON COLUMN GB_PFSA_FLEET_DIM.UPDT_BY IS 'Indicates either the program name or user ID of the person who updated the record.';


INSERT INTO PFSAWH.GB_PFSA_FLEET_DIM (FLEET_ID, FLEET_DESC, FLEET_TYPE_DESC, FLEET_SUBTYPE_DESC, FLEET_CAPABILITY_DESC) 
	VALUES (1, 'CHINOOK', 'AVIATION', 'HELICOPTER', 'CARGO') 
	
INSERT INTO PFSAWH.GB_PFSA_FLEET_DIM (FLEET_ID, FLEET_DESC, FLEET_TYPE_DESC, FLEET_SUBTYPE_DESC, FLEET_CAPABILITY_DESC) 
	VALUES (2, 'BRADLEY', 'GROUND', 'TRACKED', 'NOT APPLICABLE') 
	
-- COMMIT	
	
SELECT * 
FROM	PFSAWH.GB_PFSA_FLEET_DIM
