
CREATE TABLE GEN_MB_REF
(
  GEN_MB       VARCHAR2(2 BYTE),
  GEN_MB_DESC  VARCHAR2(20 BYTE),
  STATUS       VARCHAR2(1 BYTE),
  LST_UPDT     DATE,
  UPDT_BY      VARCHAR2(30 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE GEN_MB_REF IS 'This table contains the generic measurement bases used by PFSA in
calculating usage';

COMMENT ON COLUMN GEN_MB_REF.GEN_MB IS 'The generic measurement base';

COMMENT ON COLUMN GEN_MB_REF.GEN_MB_DESC IS 'The description of the generic measurement base';

COMMENT ON COLUMN GEN_MB_REF.STATUS IS 'THE STATUS OF THIS RECORD';

COMMENT ON COLUMN GEN_MB_REF.LST_UPDT IS 'THE SYSTEM DATE OF WHEN THIS RECORD WAS CREATED/CHANGED';

COMMENT ON COLUMN GEN_MB_REF.UPDT_BY IS 'AN IDENTIFIER OF WHAT CHANGED/CREATED THE RECORD';


CREATE UNIQUE INDEX PFSAUSAGE_PK_GEN_MB_REF ON GEN_MB_REF
(GEN_MB)
LOGGING
NOPARALLEL;


CREATE PUBLIC SYNONYM GEN_MB_REF FOR GEN_MB_REF;


ALTER TABLE GEN_MB_REF ADD (
  CONSTRAINT PFSAUSAGE_PK_GEN_MB_REF
 PRIMARY KEY
 (GEN_MB));


GRANT INSERT, SELECT, UPDATE ON  GEN_MB_REF TO C_PFSAW_DB_IN;

GRANT SELECT ON  GEN_MB_REF TO LIW_BASIC;

GRANT SELECT ON  GEN_MB_REF TO LIW_RESTRICTED;

GRANT SELECT ON  GEN_MB_REF TO S_PFSAW;

