SELECT DISTINCT LIN_HIST.LIN, 
	 LIN.INACTIVE_STATEMENT,
    SUPER.NEW_LIN, 
	 LIN.MAT_CAT_CD_1,
	 LIN.CHAP ,  
	 ITEM_CONTROL.FSC, 
	 ITEM_CONTROL.NIIN,
	 AUTH_ITEM_HIST.MSCR,
	 LIN.LONG_NOMEN,
	 LIN_HIST.DT_INACT,
	 LIN.CHAP,
	 AUTH_ITEM_HIST.ARMY_TYPE_CL_CD,
	 LIN.PUB_DT_SB_700_20,
	 ITEM_CONTROL.NOMEN_35
FROM LIN ,
	 AUTH_ITEM_HIST ,   
	 ITEM_CONTROL ,  
	 LIN_HIST 
    , SUPER      
WHERE LIN_HIST.DT_INACT IS NOT NULL AND
	 LIN_HIST.LIN = LIN.LIN AND
	 LIN.STATUS = 'H' AND
	 LIN.LIN = AUTH_ITEM_HIST.LIN AND
	 AUTH_ITEM_HIST.NIIN = ITEM_CONTROL.NIIN  
--    and item_control.niin='014818570' 
    and lin_hist.lin = super.lin (+) 
ORDER BY fsc, 
    niin, 
    LIN_HIST.lin 
    
SELECT * FROM super
