
CREATE TABLE LMI_MB_REF
(
  LMI_MB       VARCHAR2(1 BYTE)                 NOT NULL,
  LMI_MB_DESC  VARCHAR2(28 BYTE),
  STATUS       VARCHAR2(1 BYTE),
  LST_UPDT     DATE,
  UPDT_BY      VARCHAR2(30 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE LMI_MB_REF IS 'Contains measurement bases used in MIL-STD-1388-2B systems, to include POWERLOG';

COMMENT ON COLUMN LMI_MB_REF.LMI_MB IS 'The measurement base as stated in MIL-PERF-49506';

COMMENT ON COLUMN LMI_MB_REF.LMI_MB_DESC IS 'The description of the LMI measurement base.';

COMMENT ON COLUMN LMI_MB_REF.STATUS IS 'The status of the record';

COMMENT ON COLUMN LMI_MB_REF.LST_UPDT IS 'THE SYSTEM DATE OF WHEN THIS RECORD WAS CREATED/CHANGED';

COMMENT ON COLUMN LMI_MB_REF.UPDT_BY IS 'The source of the data or who changed the data';


CREATE UNIQUE INDEX PFSA_PK_LMI_MB_REF ON LMI_MB_REF
(LMI_MB)
LOGGING
NOPARALLEL;


CREATE PUBLIC SYNONYM LMI_MB_REF FOR LMI_MB_REF;


ALTER TABLE LMI_MB_REF ADD (
  CONSTRAINT PFSA_PK_LMI_MB_REF
 PRIMARY KEY
 (LMI_MB));


GRANT INSERT, SELECT, UPDATE ON  LMI_MB_REF TO C_PFSAW_DB_IN;

GRANT SELECT ON  LMI_MB_REF TO LIW_BASIC;

GRANT SELECT ON  LMI_MB_REF TO LIW_RESTRICTED;

GRANT SELECT ON  LMI_MB_REF TO S_PFSAW;

