
CREATE TABLE PFSA_STATUS_REF
(
  STATUS       VARCHAR2(1 BYTE),
  STATUS_DESC  VARCHAR2(80 BYTE),
  LST_UPDT     DATE,
  UPDT_BY      VARCHAR2(30 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE PFSA_STATUS_REF IS 'A reference table of all acceptable values of the STATUS attribute in the PFSA World';

COMMENT ON COLUMN PFSA_STATUS_REF.STATUS IS 'The status of the record in question';

COMMENT ON COLUMN PFSA_STATUS_REF.STATUS_DESC IS 'A description of the status';

COMMENT ON COLUMN PFSA_STATUS_REF.LST_UPDT IS 'THE SYSTEM DATE OF WHEN THIS RECORD WAS CREATED/CHANGED';

COMMENT ON COLUMN PFSA_STATUS_REF.UPDT_BY IS 'AN IDENTIFIER OF WHAT CHANGED/CREATED THE RECORD';


CREATE UNIQUE INDEX PK1_PFSA_STATUS_REF ON PFSA_STATUS_REF
(STATUS)
LOGGING
NOPARALLEL;


ALTER TABLE PFSA_STATUS_REF ADD (
  CONSTRAINT PK1_PFSA_STATUS_REF
 PRIMARY KEY
 (STATUS));


