
CREATE TABLE READY_STATE_REF
(
  READY_STATE       VARCHAR2(6 BYTE),
  READY_STATE_DESC  VARCHAR2(100 BYTE),
  LST_UPDT          DATE,
  UPDT_BY           VARCHAR2(30 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE READY_STATE_REF IS 'This table contains all known readiness states of a system/end item in the PFSA world';

COMMENT ON COLUMN READY_STATE_REF.READY_STATE IS 'An abbreviated identifier of the readiness state of a system/end item';

COMMENT ON COLUMN READY_STATE_REF.READY_STATE_DESC IS 'A description/definition of the readiness state';

COMMENT ON COLUMN READY_STATE_REF.LST_UPDT IS 'THE SYSTEM DATE OF WHEN THIS RECORD WAS CREATED/CHANGED';

COMMENT ON COLUMN READY_STATE_REF.UPDT_BY IS 'AN IDENTIFIER OF WHAT CHANGED/CREATED THE RECORD';


CREATE UNIQUE INDEX PK1_READY_ST_REF ON READY_STATE_REF
(READY_STATE)
LOGGING
NOPARALLEL;


ALTER TABLE READY_STATE_REF ADD (
  CONSTRAINT PK1_READY_ST_REF
 PRIMARY KEY
 (READY_STATE));


