
CREATE TABLE USAGE_MB_REF
(
  USAGE_MB       VARCHAR2(2 BYTE)               NOT NULL,
  USAGE_MB_DESC  VARCHAR2(28 BYTE),
  LMI_MB         VARCHAR2(1 BYTE)               NOT NULL,
  STATUS         VARCHAR2(1 BYTE),
  LST_UPDT       DATE,
  UPDT_BY        VARCHAR2(30 BYTE),
  GEN_MB         VARCHAR2(2 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE USAGE_MB_REF IS 'The primary reference table for usage measurement bases for the PFSA usage process.  All source measurement bases are converted to the appropriate PFSA base';

COMMENT ON COLUMN USAGE_MB_REF.USAGE_MB IS 'The measurement base of the associated usage';

COMMENT ON COLUMN USAGE_MB_REF.USAGE_MB_DESC IS 'A description of the measurement base of the associated usage';

COMMENT ON COLUMN USAGE_MB_REF.LMI_MB IS 'The measurement base as stated in MIL-PERF-49506';

COMMENT ON COLUMN USAGE_MB_REF.STATUS IS 'THE STATUS OF THIS RECORD';

COMMENT ON COLUMN USAGE_MB_REF.LST_UPDT IS 'THE SYSTEM DATE OF WHEN THIS RECORD WAS CREATED/CHANGED';

COMMENT ON COLUMN USAGE_MB_REF.UPDT_BY IS 'AN IDENTIFIER OF WHAT CHANGED/CREATED THE RECORD';

COMMENT ON COLUMN USAGE_MB_REF.GEN_MB IS 'The generic measurement base';


CREATE UNIQUE INDEX PK_USAGE_MB_REF ON USAGE_MB_REF
(USAGE_MB)
LOGGING
NOPARALLEL;


CREATE PUBLIC SYNONYM USAGE_MB_REF FOR USAGE_MB_REF;


ALTER TABLE USAGE_MB_REF ADD (
  CONSTRAINT PK_USAGE_MB_REF
 PRIMARY KEY
 (USAGE_MB));


GRANT INSERT, SELECT, UPDATE ON  USAGE_MB_REF TO C_PFSAW_DB_IN;

GRANT SELECT ON  USAGE_MB_REF TO LIW_BASIC;

GRANT SELECT ON  USAGE_MB_REF TO LIW_RESTRICTED;

GRANT SELECT ON  USAGE_MB_REF TO S_PFSAW;

