--
-- PFSA_DEBUG_STAT  (Table) 
--
CREATE TABLE PFSAWH.PFSA_DEBUG_STAT
(
  PS_PROCEDURE  VARCHAR2(30 BYTE),
  PS_OERR       VARCHAR2(6 BYTE),
  PS_LOCATION   VARCHAR2(10 BYTE),
  CALLED_BY     VARCHAR2(100 BYTE),
  PS_ID_KEY     VARCHAR2(200 BYTE),
  PS_MSG        VARCHAR2(200 BYTE),
  MSG_DT        DATE
)
TABLESPACE PFSA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          50M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

